# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020 Mellanox Technologies, Ltd

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-$(CONFIG_RTE_LIBRTE_MLX5_REGEX_PMD) += mlx5

include $(RTE_SDK)/mk/rte.subdir.mk
