/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright (C), 2025, Wuxi Stars Micro System Technologies Co., Ltd.
 */

#ifndef __SXE2_FLOW_PUBLIC_H__
#define __SXE2_FLOW_PUBLIC_H__
#include "sxe2_osal.h"

enum sxe2_flow_type {
	SXE2_FLOW_TYPE_NONE                               = 0,
	SXE2_FLOW_MAC_PAY                                 = 1,
	SXE2_FLOW_MAC_IPV4_FRAG_PAY                       = 22,
	SXE2_FLOW_MAC_IPV4_PAY                            = 23,
	SXE2_FLOW_MAC_IPV4_UDP_PAY                        = 24,
	SXE2_FLOW_MAC_IPV4_TCP_PAY                        = 26,
	SXE2_FLOW_MAC_IPV4_SCTP_PAY                       = 27,
	SXE2_FLOW_MAC_IPV4_IPV4_FRAG_PAY                  = 29,
	SXE2_FLOW_MAC_IPV4_IPV4_PAY                       = 30,
	SXE2_FLOW_MAC_IPV4_IPV4_UDP_PAY                   = 31,
	SXE2_FLOW_MAC_IPV4_IPV4_TCP_PAY                   = 33,
	SXE2_FLOW_MAC_IPV4_IPV4_SCTP_PAY                  = 34,
	SXE2_FLOW_MAC_IPV4_IPV6_FRAG_PAY                  = 36,
	SXE2_FLOW_MAC_IPV4_IPV6_PAY                       = 37,
	SXE2_FLOW_MAC_IPV4_IPV6_UDP_PAY                   = 38,
	SXE2_FLOW_MAC_IPV4_IPV6_TCP_PAY                   = 40,
	SXE2_FLOW_MAC_IPV4_IPV6_SCTP_PAY                  = 41,
	SXE2_FLOW_MAC_IPV4_GRE_PAY                        = 43,
	SXE2_FLOW_MAC_IPV4_GRE_IPV4_FRAG_PAY              = 44,
	SXE2_FLOW_MAC_IPV4_GRE_IPV4_PAY                   = 45,
	SXE2_FLOW_MAC_IPV4_GRE_IPV4_UDP_PAY               = 46,
	SXE2_FLOW_MAC_IPV4_GRE_IPV4_TCP_PAY               = 48,
	SXE2_FLOW_MAC_IPV4_GRE_IPV4_SCTP_PAY              = 49,
	SXE2_FLOW_MAC_IPV4_GRE_IPV6_FRAG_PAY              = 51,
	SXE2_FLOW_MAC_IPV4_GRE_IPV6_PAY                   = 52,
	SXE2_FLOW_MAC_IPV4_GRE_IPV6_UDP_PAY               = 53,
	SXE2_FLOW_MAC_IPV4_GRE_IPV6_TCP_PAY               = 55,
	SXE2_FLOW_MAC_IPV4_GRE_IPV6_SCTP_PAY              = 56,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_PAY                    = 58,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV4_FRAG_PAY          = 59,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV4_PAY               = 60,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV4_UDP_PAY           = 61,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV4_TCP_PAY           = 63,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV4_SCTP_PAY          = 64,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV6_FRAG_PAY          = 66,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV6_PAY               = 67,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV6_UDP_PAY           = 68,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV6_TCP_PAY           = 70,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_IPV6_SCTP_PAY          = 71,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_PAY               = 73,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV4_FRAG_PAY     = 74,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV4_PAY          = 75,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV4_UDP_PAY      = 76,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV4_TCP_PAY      = 78,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV4_SCTP_PAY     = 79,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV6_FRAG_PAY     = 81,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV6_PAY          = 82,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV6_UDP_PAY      = 83,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV6_TCP_PAY      = 85,
	SXE2_FLOW_MAC_IPV4_GRE_MAC_VLAN_IPV6_SCTP_PAY     = 86,
	SXE2_FLOW_MAC_IPV6_FRAG_PAY                       = 88,
	SXE2_FLOW_MAC_IPV6_PAY                            = 89,
	SXE2_FLOW_MAC_IPV6_UDP_PAY                        = 90,
	SXE2_FLOW_MAC_IPV6_TCP_PAY                        = 92,
	SXE2_FLOW_MAC_IPV6_SCTP_PAY                       = 93,
	SXE2_FLOW_MAC_IPV6_IPV4_FRAG_PAY                  = 95,
	SXE2_FLOW_MAC_IPV6_IPV4_PAY                       = 96,
	SXE2_FLOW_MAC_IPV6_IPV4_UDP_PAY                   = 97,
	SXE2_FLOW_MAC_IPV6_IPV4_TCP_PAY                   = 99,
	SXE2_FLOW_MAC_IPV6_IPV4_SCTP_PAY                  = 100,
	SXE2_FLOW_MAC_IPV6_IPV6_FRAG_PAY                  = 102,
	SXE2_FLOW_MAC_IPV6_IPV6_PAY                       = 103,
	SXE2_FLOW_MAC_IPV6_IPV6_UDP_PAY                   = 104,
	SXE2_FLOW_MAC_IPV6_IPV6_TCP_PAY                   = 106,
	SXE2_FLOW_MAC_IPV6_IPV6_SCTP_PAY                  = 107,
	SXE2_FLOW_MAC_IPV6_GRE_PAY                        = 109,
	SXE2_FLOW_MAC_IPV6_GRE_IPV4_FRAG_PAY              = 110,
	SXE2_FLOW_MAC_IPV6_GRE_IPV4_PAY                   = 111,
	SXE2_FLOW_MAC_IPV6_GRE_IPV4_UDP_PAY               = 112,
	SXE2_FLOW_MAC_IPV6_GRE_IPV4_TCP_PAY               = 114,
	SXE2_FLOW_MAC_IPV6_GRE_IPV4_SCTP_PAY              = 115,
	SXE2_FLOW_MAC_IPV6_GRE_IPV6_FRAG_PAY              = 117,
	SXE2_FLOW_MAC_IPV6_GRE_IPV6_PAY                   = 118,
	SXE2_FLOW_MAC_IPV6_GRE_IPV6_UDP_PAY               = 119,
	SXE2_FLOW_MAC_IPV6_GRE_IPV6_TCP_PAY               = 121,
	SXE2_FLOW_MAC_IPV6_GRE_IPV6_SCTP_PAY              = 122,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_PAY                    = 124,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV4_FRAG_PAY          = 125,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV4_PAY               = 126,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV4_UDP_PAY           = 127,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV4_TCP_PAY           = 129,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV4_SCTP_PAY          = 130,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV6_FRAG_PAY          = 132,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV6_PAY               = 133,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV6_UDP_PAY           = 134,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV6_TCP_PAY           = 136,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_IPV6_SCTP_PAY          = 137,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_PAY               = 139,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV4_FRAG_PAY     = 140,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV4_PAY          = 141,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV4_UDP_PAY      = 142,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV4_TCP_PAY      = 144,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV4_SCTP_PAY     = 145,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV6_FRAG_PAY     = 147,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV6_PAY          = 148,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV6_UDP_PAY      = 149,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV6_TCP_PAY      = 151,
	SXE2_FLOW_MAC_IPV6_GRE_MAC_VLAN_IPV6_SCTP_PAY     = 152,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_PAY                   = 329,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_PAY                   = 330,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV4_FRAG_PAY         = 331,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV4_PAY              = 332,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV4_UDP_PAY          = 333,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV4_TCP_PAY          = 334,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV4_SCTP_PAY         = 335,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV4_FRAG_PAY         = 336,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV4_PAY              = 337,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV4_UDP_PAY          = 338,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV4_TCP_PAY          = 339,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV4_SCTP_PAY         = 340,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV6_FRAG_PAY         = 341,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV6_PAY              = 342,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV6_UDP_PAY          = 343,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV6_TCP_PAY          = 344,
	SXE2_FLOW_MAC_IPV4_UDP_GTPU_IPV6_SCTP_PAY         = 345,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV6_FRAG_PAY         = 346,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV6_PAY              = 347,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV6_UDP_PAY          = 348,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV6_TCP_PAY          = 349,
	SXE2_FLOW_MAC_IPV6_UDP_GTPU_IPV6_SCTP_PAY         = 350,
	SXE2_FLOW_MAC_IPV6_MAC_PAY                        = 820,
	SXE2_FLOW_MAC_IPV6_MAC_IPV4_FRAG_PAY              = 821,
	SXE2_FLOW_MAC_IPV6_MAC_IPV4_PAY                   = 822,
	SXE2_FLOW_MAC_IPV6_MAC_IPV4_UDP_PAY               = 823,
	SXE2_FLOW_MAC_IPV6_MAC_IPV4_TCP_PAY               = 824,
	SXE2_FLOW_MAC_IPV6_MAC_IPV4_SCTP_PAY              = 825,
	SXE2_FLOW_MAC_IPV6_MAC_IPV6_FRAG_PAY              = 827,
	SXE2_FLOW_MAC_IPV6_MAC_IPV6_PAY                   = 828,
	SXE2_FLOW_MAC_IPV6_MAC_IPV6_UDP_PAY               = 829,
	SXE2_FLOW_MAC_IPV6_MAC_IPV6_TCP_PAY               = 830,
	SXE2_FLOW_MAC_IPV6_MAC_IPV6_SCTP_PAY              = 831,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_PAY                   = 835,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV4_FRAG_PAY         = 836,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV4_PAY              = 837,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV4_UDP_PAY          = 838,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV4_TCP_PAY          = 839,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV4_SCTP_PAY         = 840,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV6_FRAG_PAY         = 842,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV6_PAY              = 843,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV6_UDP_PAY          = 844,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV6_TCP_PAY          = 845,
	SXE2_FLOW_MAC_IPV6_MAC_VLAN_IPV6_SCTP_PAY         = 846,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_PAY                  = 878,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV4_FRAG_PAY        = 877,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV4_PAY             = 876,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV4_UDP_PAY         = 879,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV4_TCP_PAY         = 880,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV4_SCTP_PAY        = 875,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV6_FRAG_PAY        = 871,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV6_PAY             = 870,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV6_UDP_PAY         = 872,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV6_TCP_PAY         = 873,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_IPV6_SCTP_PAY        = 869,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_PAY                  = 891,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV4_FRAG_PAY        = 890,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV4_PAY             = 889,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV4_UDP_PAY         = 892,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV4_TCP_PAY         = 893,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV4_SCTP_PAY        = 888,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV6_FRAG_PAY        = 884,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV6_PAY             = 883,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV6_UDP_PAY         = 885,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV6_TCP_PAY         = 886,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_IPV6_SCTP_PAY        = 882,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_PAY                    = 904,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV4_FRAG_PAY          = 903,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV4_PAY               = 902,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV4_UDP_PAY           = 905,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV4_TCP_PAY           = 906,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV4_SCTP_PAY          = 901,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV6_FRAG_PAY          = 897,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV6_PAY               = 896,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV6_UDP_PAY           = 898,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV6_TCP_PAY           = 899,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_IPV6_SCTP_PAY          = 895,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_PAY                    = 917,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV4_FRAG_PAY          = 916,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV4_PAY               = 915,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV4_UDP_PAY           = 918,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV4_TCP_PAY           = 919,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV4_SCTP_PAY          = 914,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV6_FRAG_PAY          = 910,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV6_PAY               = 909,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV6_UDP_PAY           = 911,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV6_TCP_PAY           = 912,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_IPV6_SCTP_PAY          = 908,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_PAY         = 930,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV4_FRAG_PAY = 929,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV4_PAY    = 928,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV4_UDP_PAY = 931,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV4_TCP_PAY = 932,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV4_SCTP_PAY = 927,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV6_FRAG_PAY = 923,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV6_PAY    = 922,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV6_UDP_PAY = 924,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV6_TCP_PAY = 925,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_VLAN_IPV6_SCTP_PAY = 921,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_PAY         = 943,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV4_FRAG_PAY = 942,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV4_PAY    = 941,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV4_UDP_PAY = 944,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV4_TCP_PAY = 945,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV4_SCTP_PAY = 940,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV6_FRAG_PAY = 936,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV6_PAY    = 935,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV6_UDP_PAY = 937,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV6_TCP_PAY = 938,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_VLAN_IPV6_SCTP_PAY = 934,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_PAY           = 956,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV4_FRAG_PAY = 955,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV4_PAY      = 954,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV4_UDP_PAY  = 957,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV4_TCP_PAY  = 958,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV4_SCTP_PAY = 953,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV6_FRAG_PAY = 949,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV6_PAY      = 948,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV6_UDP_PAY  = 950,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV6_TCP_PAY  = 951,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_VLAN_IPV6_SCTP_PAY = 947,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_PAY           = 969,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV4_FRAG_PAY = 968,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV4_PAY      = 967,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV4_UDP_PAY  = 970,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV4_TCP_PAY  = 971,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV4_SCTP_PAY = 966,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV6_FRAG_PAY = 962,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV6_PAY      = 961,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV6_UDP_PAY  = 963,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV6_TCP_PAY  = 964,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_VLAN_IPV6_SCTP_PAY = 960,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_PAY              = 982,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV4_FRAG_PAY    = 981,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV4_PAY         = 980,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV4_UDP_PAY     = 983,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV4_TCP_PAY     = 984,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV4_SCTP_PAY    = 979,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV6_FRAG_PAY    = 975,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV6_PAY         = 974,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV6_UDP_PAY     = 976,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV6_TCP_PAY     = 977,
	SXE2_FLOW_MAC_IPV6_UDP_VXGEN_MAC_IPV6_SCTP_PAY    = 973,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_PAY              = 995,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV4_FRAG_PAY    = 994,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV4_PAY         = 993,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV4_UDP_PAY     = 996,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV4_TCP_PAY     = 997,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV4_SCTP_PAY    = 992,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV6_FRAG_PAY    = 988,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV6_PAY         = 987,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV6_UDP_PAY     = 989,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV6_TCP_PAY     = 990,
	SXE2_FLOW_MAC_IPV4_UDP_VXGEN_MAC_IPV6_SCTP_PAY    = 986,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_PAY                = 1008,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV4_FRAG_PAY      = 1007,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV4_PAY           = 1006,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV4_UDP_PAY       = 1009,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV4_TCP_PAY       = 1010,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV4_SCTP_PAY      = 1005,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV6_FRAG_PAY      = 1001,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV6_PAY           = 1000,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV6_UDP_PAY       = 1002,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV6_TCP_PAY       = 1003,
	SXE2_FLOW_MAC_IPV6_UDP_GRE_MAC_IPV6_SCTP_PAY      = 999,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_PAY                = 1021,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV4_FRAG_PAY      = 1020,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV4_PAY           = 1019,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV4_UDP_PAY       = 1022,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV4_TCP_PAY       = 1023,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV4_SCTP_PAY      = 1018,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV6_FRAG_PAY      = 1014,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV6_PAY           = 1013,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV6_UDP_PAY       = 1015,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV6_TCP_PAY       = 1016,
	SXE2_FLOW_MAC_IPV4_UDP_GRE_MAC_IPV6_SCTP_PAY      = 1012,
	SXE2_FLOW_TYPE_MAX                                = 2048,
};

enum sxe2_rss_cfg_hdr_type {
	SXE2_RSS_OUTER_HEADERS,
	SXE2_RSS_INNER_HEADERS,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV4,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV6,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV4_GRE,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV6_GRE,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV4_UDP_GRE,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV6_UDP_GRE,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV4_UDP_VXLAN,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV6_UDP_VXLAN,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV4_UDP_GENEVE,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV6_UDP_GENEVE,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV4_UDP_GTPU,

	SXE2_RSS_INNER_HEADERS_WITH_OUTER_IPV6_UDP_GTPU,
	SXE2_RSS_ANY_HEADERS
};

enum sxe2_flow_hdr {
	SXE2_FLOW_HDR_ETH = 0,
	SXE2_FLOW_HDR_VLAN,
	SXE2_FLOW_HDR_QINQ,
	SXE2_FLOW_HDR_IPV4,
	SXE2_FLOW_HDR_IPV6,
	SXE2_FLOW_HDR_ICMP = 5,
	SXE2_FLOW_HDR_TCP,
	SXE2_FLOW_HDR_UDP,
	SXE2_FLOW_HDR_SCTP,
	SXE2_FLOW_HDR_GRE,
	SXE2_FLOW_HDR_VXLAN = 10,
	SXE2_FLOW_HDR_GENEVE,
	SXE2_FLOW_HDR_GTPU,

	SXE2_FLOW_HDR_IPV_FRAG,

	SXE2_FLOW_HDR_IPV_OTHER,

	SXE2_FLOW_HDR_ETH_NON_IP = 15,
	SXE2_FLOW_HDR_MAX = 128,
};

enum sxe2_flow_fld_id {
	SXE2_FLOW_FLD_ID_ETH_DA = 0,
	SXE2_FLOW_FLD_ID_ETH_SA,
	SXE2_FLOW_FLD_ID_S_TCI,
	SXE2_FLOW_FLD_ID_C_TCI,
	SXE2_FLOW_FLD_ID_S_TPID,
	SXE2_FLOW_FLD_ID_C_TPID = 5,
	SXE2_FLOW_FLD_ID_S_VID,
	SXE2_FLOW_FLD_ID_C_VID,
	SXE2_FLOW_FLD_ID_ETH_TYPE,

	SXE2_FLOW_FLD_ID_IPV4_TOS,
	SXE2_FLOW_FLD_ID_IPV6_DSCP = 10,
	SXE2_FLOW_FLD_ID_IPV4_TTL,
	SXE2_FLOW_FLD_ID_IPV4_PROT,
	SXE2_FLOW_FLD_ID_IPV6_TTL,
	SXE2_FLOW_FLD_ID_IPV6_PROT,
	SXE2_FLOW_FLD_ID_IPV4_SA = 15,
	SXE2_FLOW_FLD_ID_IPV4_DA,
	SXE2_FLOW_FLD_ID_IPV6_SA,
	SXE2_FLOW_FLD_ID_IPV6_DA,
	SXE2_FLOW_FLD_ID_IPV4_CHKSUM,
	SXE2_FLOW_FLD_ID_IPV4_ID = 20,
	SXE2_FLOW_FLD_ID_IPV6_ID,
	SXE2_FLOW_FLD_ID_IPV6_PRE32_SA,
	SXE2_FLOW_FLD_ID_IPV6_PRE32_DA,
	SXE2_FLOW_FLD_ID_IPV6_PRE48_SA,
	SXE2_FLOW_FLD_ID_IPV6_PRE48_DA = 25,
	SXE2_FLOW_FLD_ID_IPV6_PRE64_SA,
	SXE2_FLOW_FLD_ID_IPV6_PRE64_DA,

	SXE2_FLOW_FLD_ID_TCP_SRC_PORT,
	SXE2_FLOW_FLD_ID_TCP_DST_PORT,
	SXE2_FLOW_FLD_ID_UDP_SRC_PORT = 30,
	SXE2_FLOW_FLD_ID_UDP_DST_PORT,
	SXE2_FLOW_FLD_ID_SCTP_SRC_PORT,
	SXE2_FLOW_FLD_ID_SCTP_DST_PORT,
	SXE2_FLOW_FLD_ID_TCP_FLAGS,
	SXE2_FLOW_FLD_ID_TCP_CHKSUM = 35,
	SXE2_FLOW_FLD_ID_UDP_CHKSUM,
	SXE2_FLOW_FLD_ID_SCTP_CHKSUM,

	SXE2_FLOW_FLD_ID_VXLAN_VNI,

	SXE2_FLOW_FLD_ID_GENEVE_VNI,

	SXE2_FLOW_FLD_ID_GTPU_TEID = 40,

	SXE2_FLOW_FLD_ID_NVGRE_TNI,

	SXE2_FLOW_FLD_ID_MAX = 128,
};

struct sxe2_ether_hdr {
	uint8_t dst_addr[SXE2_ETH_ALEN];
	uint8_t src_addr[SXE2_ETH_ALEN];
	uint16_t  ether_type;
};

struct sxe2_vlan_hdr {
	uint16_t  type;
	uint16_t  vlan;
};

struct sxe2_ipv4_hdr {
	uint8_t ver_ihl;
	uint8_t tos;
	uint16_t  tot_len;
	uint16_t  id;
	uint16_t  frag_off;
	uint8_t ttl;
	uint8_t protocol;
	uint16_t  check;
	uint32_t saddr;
	uint32_t daddr;
};
#define SXE2_IPV6_ADDR_LENGTH        (16)
#define SXE2_IPV6_TC_SHIFT (20)
#define SXE2_IPV6_TC_MASK  (0xFF)

struct sxe2_ipv6_hdr {
	uint32_t pri_ver_flow;
	uint16_t  payload_len;
	uint8_t nexthdr;
	uint8_t hop_limit;
	union {
		uint8_t saddr[16];
		uint16_t	saddr16[8];
		uint32_t	saddr32[4];
	};
	union {
		uint8_t daddr[16];
		uint16_t	daddr16[8];
		uint32_t	daddr32[4];
	};
};

struct sxe2_tcp_hdr {
	uint16_t  source;
	uint16_t  dest;
	uint32_t seq;
	uint32_t ack_seq;
	uint16_t  flag;
	uint16_t  window;
	uint16_t  check;
	uint16_t  urg_ptr;
};

struct sxe2_udp_hdr {
	uint16_t  source;
	uint16_t  dest;
	uint16_t  len;
	uint16_t  check;
};

struct sxe2_sctp_hdr {
	uint16_t src_port;
	uint16_t dst_port;
};

struct sxe2_nvgre_hdr {
	uint16_t flags;
	uint16_t protocol;
	uint32_t tni;
};
struct sxe2_geneve_hdr {
	uint16_t flags;
	uint16_t protocol;
	uint32_t vni;
};
struct sxe2_gtpu_hdr {
	uint8_t flag;
	uint8_t msg_type;
	uint16_t msg_len;
	uint32_t teid;
};
struct sxe2_vxlan_hdr {
	uint8_t flag;
	uint8_t resvd0;
	uint8_t resvd1;
	uint8_t protocol;
	uint32_t vni;
};

enum sxe2_flow_act_type {
	SXE2_FLOW_ACTION_DROP = 0,
	SXE2_FLOW_ACTION_TC_REDIRECT,
	SXE2_FLOW_ACTION_TO_VSI,
	SXE2_FLOW_ACTION_TO_VSI_LIST,
	SXE2_FLOW_ACTION_PASSTHRU,
	SXE2_FLOW_ACTION_QUEUE,
	SXE2_FLOW_ACTION_Q_REGION,
	SXE2_FLOW_ACTION_MARK,
	SXE2_FLOW_ACTION_COUNT,
	SXE2_FLOW_ACTION_RSS,
	SXE2_FLOW_ACTION_MAX = 32,
};

enum sxe2_rss_hash_key_func {
	SXE2_RSS_HASH_FUNC_TOEPLITZ     = 0,
	SXE2_RSS_HASH_FUNC_SYM_TOEPLITZ = 1,
	SXE2_RSS_HASH_FUNC_XOR          = 2,
	SXE2_RSS_HASH_FUNC_JEKINS       = 3
};

struct sxe2_flow_action_rss {
	DECLARE_BITMAP(hdr_out, SXE2_FLOW_HDR_MAX);
	DECLARE_BITMAP(hdr_in, SXE2_FLOW_HDR_MAX);
	DECLARE_BITMAP(fld, SXE2_FLOW_FLD_ID_MAX);
	uint8_t is_inner;
	uint8_t func;
	uint8_t hdr_type;
};

struct sxe2_flow_action_queue {
	uint16_t vsi_index;
	uint16_t q_index;
};

struct sxe2_flow_action_queue_region {
	uint16_t vsi_index;
	uint16_t q_index;
	uint8_t region;
};

struct sxe2_flow_action_passthru {
	uint16_t vsi_index;
};

struct sxe2_flow_action_mark {
	uint32_t mark_id;
};

#define SXE2_VSI_MAX (2048)
struct sxe2_flow_action_vsi {
	uint16_t vsi_index;
};

struct sxe2_flow_action_vsi_list {
	DECLARE_BITMAP(vsi_list_map, SXE2_VSI_MAX);
	uint16_t vsi_cnt;
};

enum sxe2_fnav_stat_ctrl_type {
	SXE2_FNAV_STAT_ENA_NONE = 0,
	SXE2_FNAV_STAT_ENA_PKTS,
	SXE2_FNAV_STAT_ENA_BYTES,
	SXE2_FNAV_STAT_ENA_ALL,
};

struct sxe2_flow_action_count {
	uint32_t user_id;
	uint32_t driver_id;
	uint32_t stat_index;
	uint32_t stat_ctrl;
};

enum sxe2_flow_engine_type {
	SXE2_FLOW_ENGINE_ACL,
	SXE2_FLOW_ENGINE_SWITCH,
	SXE2_FLOW_ENGINE_FNAV,
	SXE2_FLOW_ENGINE_RSS,
	SXE2_FLOW_ENGINE_MAX,
};

struct sxe2_flow_item {
	struct sxe2_ether_hdr eth;
	struct sxe2_vlan_hdr vlan;
	struct sxe2_vlan_hdr qinq;
	struct sxe2_ipv4_hdr ipv4;
	struct sxe2_ipv6_hdr ipv6;
	struct sxe2_udp_hdr udp;
	struct sxe2_tcp_hdr tcp;
	struct sxe2_sctp_hdr sctp;
	struct sxe2_gtpu_hdr gtpu;
	struct sxe2_vxlan_hdr vxlan;
	struct sxe2_nvgre_hdr nvgre;
	struct sxe2_geneve_hdr geneve;
};

enum sxe2_flow_sw_direct_type {
	SXE2_FLOW_SW_DIRECT_TX,
	SXE2_FLOW_SW_DIRECT_RX,
	SXE2_FLOW_SW_DIRECT_MAX,
};
enum sxe2_flow_sw_pattern_type {
	SXE2_FLOW_SW_PATTERN_ONLY,
	SXE2_FLOW_SW_PATTERN_LAST,
	SXE2_FLOW_SW_PATTERN_FIRST,
	SXE2_FLOW_SW_PATTERN_MAX,
};

enum sxe2_flow_tunnel_type {
	SXE2_FLOW_TUNNEL_TYPE_NONE,
	SXE2_FLOW_TUNNEL_TYPE_PARENT,
	SXE2_FLOW_TUNNEL_TYPE_VXLAN,
	SXE2_FLOW_TUNNEL_TYPE_GTPU,
	SXE2_FLOW_TUNNEL_TYPE_GENEVE,
	SXE2_FLOW_TUNNEL_TYPE_GRE,
	SXE2_FLOW_TUNNEL_TYPE_IPIP,
};

struct sxe2_flow_meta {
	uint8_t switch_pattern_dup_allow;
	uint8_t switch_src_direct;
	uint16_t flow_src_vsi;
	uint16_t flow_rule_vsi;
	uint32_t flow_prio;
	uint16_t flow_type;
	uint8_t tunnel_type;
	uint8_t rsv;
};

struct sxe2_flow_pattern {
	DECLARE_BITMAP(hdrs, SXE2_FLOW_HDR_MAX);
	DECLARE_BITMAP(map_spec, SXE2_FLOW_FLD_ID_MAX);
	DECLARE_BITMAP(map_mask, SXE2_FLOW_FLD_ID_MAX);
	struct sxe2_flow_item item_spec;
	struct sxe2_flow_item item_mask;
	uint64_t rss_type_allow;
};

struct sxe2_flow_action {
	DECLARE_BITMAP(act_types, SXE2_FLOW_ACTION_MAX);
	struct sxe2_flow_action_rss rss;
	struct sxe2_flow_action_queue queue;
	struct sxe2_flow_action_queue_region q_region;
	struct sxe2_flow_action_passthru passthru;
	struct sxe2_flow_action_vsi vsi;
	struct sxe2_flow_action_vsi_list vsi_list;
	struct sxe2_flow_action_mark mark;
	struct sxe2_flow_action_count count;
};
#endif /* __SXE2_FLOW_PUBLIC_H__ */
