/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2025 Huawei Technologies Co., Ltd
 */

#ifndef _HINIC3_CMD_H_
#define _HINIC3_CMD_H_

#define NIC_RSS_TEMP_ID_TO_CTX_LT_IDX(tmp_id)	tmp_id
/* Begin of one temp tbl. */
#define NIC_RSS_TEMP_ID_TO_INDIR_LT_IDX(tmp_id)	((tmp_id) << 4)
/* 4 ctx in one entry. */
#define NIC_RSS_CTX_TBL_ENTRY_SIZE		0x10
/* Entry size = 16B, 16 entry/template. */
#define NIC_RSS_INDIR_TBL_ENTRY_SIZE		0x10
/* Entry size = 16B, so entry_num = 256B/16B. */
#define NIC_RSS_INDIR_TBL_ENTRY_NUM		0x10

#define NIC_UP_RSS_INVALID_TEMP_ID		0xFF
#define NIC_UP_RSS_INVALID_FUNC_ID		0xFFFF
#define NIC_UP_RSS_INVALID			0x00
#define NIC_UP_RSS_EN				0x01
#define NIC_UP_RSS_INVALID_GROUP_ID		0x7F

#define NIC_RSS_CMD_TEMP_ALLOC			0x01
#define NIC_RSS_CMD_TEMP_FREE			0x02

#define HINIC3_RSS_TYPE_VALID_SHIFT		23
#define HINIC3_RSS_TYPE_TCP_IPV6_EXT_SHIFT	24
#define HINIC3_RSS_TYPE_IPV6_EXT_SHIFT		25
#define HINIC3_RSS_TYPE_TCP_IPV6_SHIFT		26
#define HINIC3_RSS_TYPE_IPV6_SHIFT		27
#define HINIC3_RSS_TYPE_TCP_IPV4_SHIFT		28
#define HINIC3_RSS_TYPE_IPV4_SHIFT		29
#define HINIC3_RSS_TYPE_UDP_IPV6_SHIFT		30
#define HINIC3_RSS_TYPE_UDP_IPV4_SHIFT		31
#define HINIC3_RSS_TYPE_SET(val, member)	\
	(((u32)(val) & 0x1) << HINIC3_RSS_TYPE_##member##_SHIFT)

#define HINIC3_RSS_TYPE_GET(val, member)	\
	(((u32)(val) >> HINIC3_RSS_TYPE_##member##_SHIFT) & 0x1)

/* NIC CMDQ MODE. */
typedef enum hinic3_ucode_cmd {
	HINIC3_UCODE_CMD_MODIFY_QUEUE_CTX = 0,
	HINIC3_UCODE_CMD_CLEAN_QUEUE_CONTEXT,
	HINIC3_UCODE_CMD_ARM_SQ,
	HINIC3_UCODE_CMD_ARM_RQ,
	HINIC3_UCODE_CMD_SET_RSS_INDIR_TABLE,
	HINIC3_UCODE_CMD_SET_RSS_CONTEXT_TABLE,
	HINIC3_UCODE_CMD_GET_RSS_INDIR_TABLE,
	HINIC3_UCODE_CMD_GET_RSS_CONTEXT_TABLE,
	HINIC3_UCODE_CMD_SET_IQ_ENABLE,
	HINIC3_UCODE_CMD_SET_RQ_FLUSH = 10,
	HINIC3_UCODE_CMD_MODIFY_VLAN_CTX,
} cmdq_nic_subtype_e;

/* Commands between NIC to MPU. */
enum hinic3_nic_cmd {
	/* Only for PFD and VFD. */
	HINIC3_NIC_CMD_VF_REGISTER = 0,

	/* FUNC CFG */
	HINIC3_NIC_CMD_SET_FUNC_TBL = 5,
	HINIC3_NIC_CMD_SET_VPORT_ENABLE,
	HINIC3_NIC_CMD_SET_RX_MODE,
	HINIC3_NIC_CMD_SQ_CI_ATTR_SET,
	HINIC3_NIC_CMD_GET_VPORT_STAT,
	HINIC3_NIC_CMD_CLEAN_VPORT_STAT,
	HINIC3_NIC_CMD_CLEAR_QP_RESOURCE,
	HINIC3_NIC_CMD_CFG_FLEX_QUEUE,
	/* LRO CFG */
	HINIC3_NIC_CMD_CFG_RX_LRO,
	HINIC3_NIC_CMD_CFG_LRO_TIMER,
	HINIC3_NIC_CMD_FEATURE_NEGO,

	/* MAC & VLAN CFG */
	HINIC3_NIC_CMD_GET_MAC = 20,
	HINIC3_NIC_CMD_SET_MAC,
	HINIC3_NIC_CMD_DEL_MAC,
	HINIC3_NIC_CMD_UPDATE_MAC,
	HINIC3_NIC_CMD_GET_ALL_DEFAULT_MAC,

	HINIC3_NIC_CMD_CFG_FUNC_VLAN,
	HINIC3_NIC_CMD_SET_VLAN_FILTER_EN,
	HINIC3_NIC_CMD_SET_RX_VLAN_OFFLOAD,

	/* SR-IOV */
	HINIC3_NIC_CMD_CFG_VF_VLAN = 40,
	HINIC3_NIC_CMD_SET_SPOOPCHK_STATE,
	/* RATE LIMIT */
	HINIC3_NIC_CMD_SET_MAX_MIN_RATE,

	/* RSS CFG */
	HINIC3_NIC_CMD_RSS_CFG = 60,
	HINIC3_NIC_CMD_RSS_TEMP_MGR,
	HINIC3_NIC_CMD_GET_RSS_CTX_TBL,
	HINIC3_NIC_CMD_CFG_RSS_HASH_KEY,
	HINIC3_NIC_CMD_CFG_RSS_HASH_ENGINE,
	HINIC3_NIC_CMD_SET_RSS_CTX_TBL_INTO_FUNC,

	/* FDIR */
	HINIC3_NIC_CMD_ADD_TC_FLOW = 80,
	HINIC3_NIC_CMD_DEL_TC_FLOW,
	HINIC3_NIC_CMD_GET_TC_FLOW,
	HINIC3_NIC_CMD_FLUSH_TCAM,
	HINIC3_NIC_CMD_CFG_TCAM_BLOCK,
	HINIC3_NIC_CMD_ENABLE_TCAM,
	HINIC3_NIC_CMD_GET_TCAM_BLOCK,

	HINIC3_NIC_CMD_SET_FDIR_STATUS = 91,

	/* PORT CFG */
	HINIC3_NIC_CMD_SET_PORT_ENABLE = 100,
	HINIC3_NIC_CMD_CFG_PAUSE_INFO,

	HINIC3_NIC_CMD_SET_PORT_CAR,
	HINIC3_NIC_CMD_SET_ER_DROP_PKT,

	HINIC3_NIC_CMD_VF_COS,
	HINIC3_NIC_CMD_SETUP_COS_MAPPING,
	HINIC3_NIC_CMD_SET_ETS,
	HINIC3_NIC_CMD_SET_PFC,

	/* MISC */
	HINIC3_NIC_CMD_BIOS_CFG = 120,
	HINIC3_NIC_CMD_SET_FIRMWARE_CUSTOM_PACKETS_MSG,

	/* DFX */
	HINIC3_NIC_CMD_GET_SM_TABLE = 140,
	HINIC3_NIC_CMD_RD_LINE_TBL,

	HINIC3_NIC_CMD_SET_VHD_CFG = 161,

	HINIC3_NIC_CMD_GET_PORT_STAT = 200,
	HINIC3_NIC_CMD_CLEAN_PORT_STAT,

	HINIC3_NIC_CMD_MAX = 256
};

/* COMM commands between driver to MPU. */
enum hinic3_mgmt_cmd {
	HINIC3_MGMT_CMD_FUNC_RESET = 0,
	HINIC3_MGMT_CMD_FEATURE_NEGO,
	HINIC3_MGMT_CMD_FLUSH_DOORBELL,
	HINIC3_MGMT_CMD_START_FLUSH,
	HINIC3_MGMT_CMD_SET_FUNC_FLR,
	HINIC3_MGMT_CMD_SET_FUNC_SVC_USED_STATE = 7,

	HINIC3_MGMT_CMD_CFG_MSIX_NUM = 10,

	HINIC3_MGMT_CMD_SET_CMDQ_CTXT = 20,
	HINIC3_MGMT_CMD_SET_VAT,
	HINIC3_MGMT_CMD_CFG_PAGESIZE,
	HINIC3_MGMT_CMD_CFG_MSIX_CTRL_REG,
	HINIC3_MGMT_CMD_SET_CEQ_CTRL_REG,
	HINIC3_MGMT_CMD_SET_DMA_ATTR,

	HINIC3_MGMT_CMD_GET_MQM_FIX_INFO = 40,
	HINIC3_MGMT_CMD_SET_MQM_CFG_INFO,
	HINIC3_MGMT_CMD_SET_MQM_SRCH_GPA,
	HINIC3_MGMT_CMD_SET_PPF_TMR,
	HINIC3_MGMT_CMD_SET_PPF_HT_GPA,
	HINIC3_MGMT_CMD_SET_FUNC_TMR_BITMAT,

	HINIC3_MGMT_CMD_GET_FW_VERSION = 60,
	HINIC3_MGMT_CMD_GET_BOARD_INFO,
	HINIC3_MGMT_CMD_SYNC_TIME,
	HINIC3_MGMT_CMD_GET_HW_PF_INFOS,
	HINIC3_MGMT_CMD_SEND_BDF_INFO,

	HINIC3_MGMT_CMD_UPDATE_FW = 80,
	HINIC3_MGMT_CMD_ACTIVE_FW,
	HINIC3_MGMT_CMD_HOT_ACTIVE_FW,
	HINIC3_MGMT_CMD_HOT_ACTIVE_DONE_NOTICE,
	HINIC3_MGMT_CMD_SWITCH_CFG,
	HINIC3_MGMT_CMD_CHECK_FLASH,
	HINIC3_MGMT_CMD_CHECK_FLASH_RW,
	HINIC3_MGMT_CMD_RESOURCE_CFG,
	HINIC3_MGMT_CMD_UPDATE_BIOS,

	HINIC3_MGMT_CMD_FAULT_REPORT = 100,
	HINIC3_MGMT_CMD_WATCHDOG_INFO,
	HINIC3_MGMT_CMD_MGMT_RESET,
	HINIC3_MGMT_CMD_FFM_SET,

	HINIC3_MGMT_CMD_GET_LOG = 120,
	HINIC3_MGMT_CMD_TEMP_OP,
	HINIC3_MGMT_CMD_EN_AUTO_RST_CHIP,
	HINIC3_MGMT_CMD_CFG_REG,
	HINIC3_MGMT_CMD_GET_CHIP_ID,
	HINIC3_MGMT_CMD_SYSINFO_DFX,
	HINIC3_MGMT_CMD_PCIE_DFX_NTC,
};

enum mag_cmd {
	SERDES_CMD_PROCESS = 0,

	MAG_CMD_SET_PORT_CFG      = 1,
	MAG_CMD_SET_PORT_ADAPT    = 2,
	MAG_CMD_CFG_LOOPBACK_MODE = 3,

	MAG_CMD_GET_PORT_ENABLE   = 5,
	MAG_CMD_SET_PORT_ENABLE   = 6,
	MAG_CMD_GET_LINK_STATUS   = 7,
	MAG_CMD_SET_LINK_FOLLOW   = 8,
	MAG_CMD_SET_PMA_ENABLE    = 9,
	MAG_CMD_CFG_FEC_MODE      = 10,

	/* PHY */
	MAG_CMD_GET_XSFP_INFO        = 60,
	MAG_CMD_SET_XSFP_ENABLE      = 61,
	MAG_CMD_GET_XSFP_PRESENT     = 62,
	/* sfp/qsfp single byte read/write, for equipment test. */
	MAG_CMD_SET_XSFP_RW          = 63,
	MAG_CMD_CFG_XSFP_TEMPERATURE = 64,

	MAG_CMD_WIRE_EVENT        = 100,
	MAG_CMD_LINK_ERR_EVENT    = 101,

	MAG_CMD_EVENT_PORT_INFO   = 150,
	MAG_CMD_GET_PORT_STAT     = 151,
	MAG_CMD_CLR_PORT_STAT     = 152,
	MAG_CMD_GET_PORT_INFO     = 153,
	MAG_CMD_GET_PCS_ERR_CNT   = 154,
	MAG_CMD_GET_MAG_CNT       = 155,
	MAG_CMD_DUMP_ANTRAIN_INFO = 156,

	MAG_CMD_MAX = 0xFF
};

#endif /* _HINIC3_CMD_H_ */
