;
; Supported features of the 'af_xdp' network poll mode driver.
;
; Refer to default.ini for the full list of available PMD features.
;
[Features]
Power mgmt address monitor = Y
MTU update           = Y
Promiscuous mode     = Y
Timestamp offload    = Y
Stats per queue      = Y
Multiprocess aware   = Y
x86-64               = Y
