;
; Supported features of the 'nfb' network poll mode driver.
;
; Refer to default.ini for the full list of available PMD features.
;
[Features]
Speed capabilities   = P
Queue start/stop     = Y
Promiscuous mode     = Y
Allmulticast mode    = Y
Unicast MAC filter   = Y
Timestamp offload    = P
Extended stats       = Y
Stats per queue      = Y
FW version           = Y
Multiprocess aware   = Y
Linux                = Y
x86-64               = Y
