;
; Supported features of the 'sxe2' network poll mode driver.
;
; Refer to default.ini for the full list of available PMD features.
;
; A feature with "P" indicates only be supported when non-vector path
; is selected.
;
[Features]
Speed capabilities   = Y
Link status          = Y
Link status event    = Y
Rx interrupt         = Y
Fast mbuf free       = P
Free Tx mbuf on demand = Y
Burst mode info      = Y
Queue start/stop     = Y
Power mgmt address monitor = Y
Buffer split on Rx   = P
Scattered Rx         = Y
Traffic manager      = Y
CRC offload          = Y
VLAN offload         = Y
QinQ offload         = P
L3 checksum offload  = Y
L4 checksum offload  = Y
Timestamp offload    = P
Inner L3 checksum    = P
Inner L4 checksum    = P
Rx descriptor status = Y
Tx descriptor status = Y
MTU update           = Y
TSO                  = P
Promiscuous mode     = Y
Allmulticast mode    = Y
Unicast MAC filter   = Y
RSS hash             = Y
RSS key update       = Y
RSS reta update      = Y
VLAN filter          = Y
Inline crypto        = Y
Packet type parsing  = Y
Timesync             = Y
Basic stats          = Y
Extended stats       = Y
FW version           = Y
Module EEPROM dump   = Y
Multiprocess aware   = Y
Linux                = Y
x86-32               = Y
x86-64               = Y

[rte_flow items]
eth                  = P
geneve               = Y
gre                  = Y
gtpu                 = Y
ipv4                 = Y
ipv6                 = Y
ipv6_frag_ext        = Y
nvgre                = Y
sctp                 = Y
tcp                  = Y
udp                  = Y
vlan                 = P
vxlan                = Y
vxlan_gpe            = Y

[rte_flow actions]
count                = Y
drop                 = Y
mark                 = Y
passthru             = Y
port_representor     = Y
queue                = Y
represented_port     = Y
rss                  = Y
send_to_kernel       = Y
port_id              = Y
