/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright 2016 6WIND S.A.
 * Copyright 2016 Mellanox Technologies, Ltd
 * Copyright 2026 DynaNIC Semiconductors, Ltd.
 */

/**
 * @file
 * Extended flow parser API for testpmd-like CLI integration.
 *
 * This header exposes experimental functions, structures, and configuration
 * accessors for building testpmd-like flow command interfaces. These APIs
 * provide full CLI integration including encapsulation configuration,
 * cmdline token handling, and command dispatch.
 *
 * For simple string-to-flow parsing, use the lightweight helpers in
 * rte_flow_parser.h instead.
 *
 * This header includes the public API (rte_flow_parser.h) automatically.
 */

#ifndef _RTE_FLOW_PARSER_PRIVATE_H_
#define _RTE_FLOW_PARSER_PRIVATE_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <cmdline_parse.h>
#include <rte_flow.h>
#include <rte_ip.h>
#include <rte_ether.h>

/* Include the public API */
#include <rte_flow_parser.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Shared limits used across parser helpers. */
#define ACTION_RAW_ENCAP_MAX_DATA 512
#define RAW_ENCAP_CONFS_MAX_NUM 8
#define ACTION_IPV6_EXT_PUSH_MAX_DATA 512
#define IPV6_EXT_PUSH_CONFS_MAX_NUM 8
#define ACTION_SAMPLE_ACTIONS_NUM 10
#define RAW_SAMPLE_CONFS_MAX_NUM 8
#define ACTION_RSS_QUEUE_NUM 128
#define ACTION_VXLAN_ENCAP_ITEMS_NUM 6
#define ACTION_NVGRE_ENCAP_ITEMS_NUM 5

/* Reset parser defaults and clear stored caches. */
__rte_experimental
void rte_flow_parser_reset_defaults(void);

struct rte_flow_parser_vxlan_encap_conf {
	uint32_t select_ipv4:1;
	uint32_t select_vlan:1;
	uint32_t select_tos_ttl:1;
	uint8_t vni[3];
	rte_be16_t udp_src;
	rte_be16_t udp_dst;
	rte_be32_t ipv4_src;
	rte_be32_t ipv4_dst;
	struct rte_ipv6_addr ipv6_src;
	struct rte_ipv6_addr ipv6_dst;
	rte_be16_t vlan_tci;
	uint8_t ip_tos;
	uint8_t ip_ttl;
	struct rte_ether_addr eth_src;
	struct rte_ether_addr eth_dst;
};

struct rte_flow_parser_nvgre_encap_conf {
	uint32_t select_ipv4:1;
	uint32_t select_vlan:1;
	uint8_t tni[3];
	rte_be32_t ipv4_src;
	rte_be32_t ipv4_dst;
	struct rte_ipv6_addr ipv6_src;
	struct rte_ipv6_addr ipv6_dst;
	rte_be16_t vlan_tci;
	struct rte_ether_addr eth_src;
	struct rte_ether_addr eth_dst;
};

struct rte_flow_parser_l2_encap_conf {
	uint32_t select_ipv4:1;
	uint32_t select_vlan:1;
	rte_be16_t vlan_tci;
	struct rte_ether_addr eth_src;
	struct rte_ether_addr eth_dst;
};

struct rte_flow_parser_l2_decap_conf {
	uint32_t select_vlan:1;
};

struct rte_flow_parser_mplsogre_encap_conf {
	uint32_t select_ipv4:1;
	uint32_t select_vlan:1;
	uint8_t label[3];
	rte_be32_t ipv4_src;
	rte_be32_t ipv4_dst;
	struct rte_ipv6_addr ipv6_src;
	struct rte_ipv6_addr ipv6_dst;
	rte_be16_t vlan_tci;
	uint8_t eth_src[RTE_ETHER_ADDR_LEN];
	uint8_t eth_dst[RTE_ETHER_ADDR_LEN];
};

struct rte_flow_parser_mplsogre_decap_conf {
	uint32_t select_ipv4:1;
	uint32_t select_vlan:1;
};

struct rte_flow_parser_mplsoudp_encap_conf {
	uint32_t select_ipv4:1;
	uint32_t select_vlan:1;
	uint8_t label[3];
	rte_be16_t udp_src;
	rte_be16_t udp_dst;
	rte_be32_t ipv4_src;
	rte_be32_t ipv4_dst;
	struct rte_ipv6_addr ipv6_src;
	struct rte_ipv6_addr ipv6_dst;
	rte_be16_t vlan_tci;
	uint8_t eth_src[RTE_ETHER_ADDR_LEN];
	uint8_t eth_dst[RTE_ETHER_ADDR_LEN];
};

struct rte_flow_parser_mplsoudp_decap_conf {
	uint32_t select_ipv4:1;
	uint32_t select_vlan:1;
};

/* Accessors for mutable encap/decap configurations. */
__rte_experimental
struct rte_flow_parser_vxlan_encap_conf *rte_flow_parser_vxlan_encap_conf(void);
__rte_experimental
struct rte_flow_parser_nvgre_encap_conf *rte_flow_parser_nvgre_encap_conf(void);
__rte_experimental
struct rte_flow_parser_l2_encap_conf *rte_flow_parser_l2_encap_conf(void);
__rte_experimental
struct rte_flow_parser_l2_decap_conf *rte_flow_parser_l2_decap_conf(void);
__rte_experimental
struct rte_flow_parser_mplsogre_encap_conf *rte_flow_parser_mplsogre_encap_conf(void);
__rte_experimental
struct rte_flow_parser_mplsogre_decap_conf *rte_flow_parser_mplsogre_decap_conf(void);
__rte_experimental
struct rte_flow_parser_mplsoudp_encap_conf *rte_flow_parser_mplsoudp_encap_conf(void);
__rte_experimental
struct rte_flow_parser_mplsoudp_decap_conf *rte_flow_parser_mplsoudp_decap_conf(void);

/* Raw encap/decap configuration accessors. */
__rte_experimental
const struct rte_flow_action_raw_encap *rte_flow_parser_raw_encap_conf_get(uint16_t index);

__rte_experimental
const struct rte_flow_action_raw_decap *rte_flow_parser_raw_decap_conf_get(uint16_t index);

/* Conntrack context accessor. */
__rte_experimental
struct rte_flow_action_conntrack *rte_flow_parser_conntrack_context(void);

/**
 * Tunnel steering/match flags used by the parser.
 */
struct rte_flow_parser_tunnel_ops {
	uint32_t id;
	char type[16];
	uint32_t enabled:1;
	uint32_t actions:1;
	uint32_t items:1;
};

/** Parser token indices. */
enum rte_flow_parser_command_index {
	/* Special tokens. */
	RTE_FLOW_PARSER_CMD_ZERO = 0,
	RTE_FLOW_PARSER_CMD_END,
	RTE_FLOW_PARSER_CMD_START_SET,
	RTE_FLOW_PARSER_CMD_END_SET,

	/* Common tokens. */
	RTE_FLOW_PARSER_CMD_COMMON_INTEGER,
	RTE_FLOW_PARSER_CMD_COMMON_UNSIGNED,
	RTE_FLOW_PARSER_CMD_COMMON_PREFIX,
	RTE_FLOW_PARSER_CMD_COMMON_BOOLEAN,
	RTE_FLOW_PARSER_CMD_COMMON_STRING,
	RTE_FLOW_PARSER_CMD_COMMON_HEX,
	RTE_FLOW_PARSER_CMD_COMMON_FILE_PATH,
	RTE_FLOW_PARSER_CMD_COMMON_MAC_ADDR,
	RTE_FLOW_PARSER_CMD_COMMON_IPV4_ADDR,
	RTE_FLOW_PARSER_CMD_COMMON_IPV6_ADDR,
	RTE_FLOW_PARSER_CMD_COMMON_RULE_ID,
	RTE_FLOW_PARSER_CMD_COMMON_PORT_ID,
	RTE_FLOW_PARSER_CMD_COMMON_GROUP_ID,
	RTE_FLOW_PARSER_CMD_COMMON_PRIORITY_LEVEL,
	RTE_FLOW_PARSER_CMD_COMMON_INDIRECT_ACTION_ID,
	RTE_FLOW_PARSER_CMD_COMMON_PROFILE_ID,
	RTE_FLOW_PARSER_CMD_COMMON_POLICY_ID,
	RTE_FLOW_PARSER_CMD_COMMON_FLEX_HANDLE,
	RTE_FLOW_PARSER_CMD_COMMON_FLEX_TOKEN,
	RTE_FLOW_PARSER_CMD_COMMON_PATTERN_TEMPLATE_ID,
	RTE_FLOW_PARSER_CMD_COMMON_ACTIONS_TEMPLATE_ID,
	RTE_FLOW_PARSER_CMD_COMMON_TABLE_ID,
	RTE_FLOW_PARSER_CMD_COMMON_QUEUE_ID,
	RTE_FLOW_PARSER_CMD_COMMON_METER_COLOR_NAME,

	/* TOP-level command. */
	RTE_FLOW_PARSER_CMD_ADD,

	/* Top-level command. */
	RTE_FLOW_PARSER_CMD_SET,
	/* Sub-leve commands. */
	RTE_FLOW_PARSER_CMD_SET_RAW_ENCAP,
	RTE_FLOW_PARSER_CMD_SET_RAW_DECAP,
	RTE_FLOW_PARSER_CMD_SET_RAW_INDEX,
	RTE_FLOW_PARSER_CMD_SET_SAMPLE_ACTIONS,
	RTE_FLOW_PARSER_CMD_SET_SAMPLE_INDEX,
	RTE_FLOW_PARSER_CMD_SET_IPV6_EXT_REMOVE,
	RTE_FLOW_PARSER_CMD_SET_IPV6_EXT_PUSH,
	RTE_FLOW_PARSER_CMD_SET_IPV6_EXT_INDEX,

	/* Top-level command. */
	RTE_FLOW_PARSER_CMD_FLOW,
	/* Sub-level commands. */
	RTE_FLOW_PARSER_CMD_INFO,
	RTE_FLOW_PARSER_CMD_CONFIGURE,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE,
	RTE_FLOW_PARSER_CMD_TABLE,
	RTE_FLOW_PARSER_CMD_FLOW_GROUP,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION,
	RTE_FLOW_PARSER_CMD_VALIDATE,
	RTE_FLOW_PARSER_CMD_CREATE,
	RTE_FLOW_PARSER_CMD_DESTROY,
	RTE_FLOW_PARSER_CMD_UPDATE,
	RTE_FLOW_PARSER_CMD_FLUSH,
	RTE_FLOW_PARSER_CMD_DUMP,
	RTE_FLOW_PARSER_CMD_QUERY,
	RTE_FLOW_PARSER_CMD_LIST,
	RTE_FLOW_PARSER_CMD_AGED,
	RTE_FLOW_PARSER_CMD_ISOLATE,
	RTE_FLOW_PARSER_CMD_TUNNEL,
	RTE_FLOW_PARSER_CMD_FLEX,
	RTE_FLOW_PARSER_CMD_QUEUE,
	RTE_FLOW_PARSER_CMD_PUSH,
	RTE_FLOW_PARSER_CMD_PULL,
	RTE_FLOW_PARSER_CMD_HASH,

	/* Flex arguments */
	RTE_FLOW_PARSER_CMD_FLEX_ITEM_CREATE,
	RTE_FLOW_PARSER_CMD_FLEX_ITEM_DESTROY,

	/* Pattern template arguments. */
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_CREATE,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_DESTROY,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_CREATE_ID,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_DESTROY_ID,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_RELAXED_MATCHING,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_INGRESS,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_EGRESS,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_TRANSFER,
	RTE_FLOW_PARSER_CMD_PATTERN_TEMPLATE_SPEC,

	/* Actions template arguments. */
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_CREATE,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_DESTROY,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_CREATE_ID,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_DESTROY_ID,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_INGRESS,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_EGRESS,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_TRANSFER,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_SPEC,
	RTE_FLOW_PARSER_CMD_ACTIONS_TEMPLATE_MASK,

	/* Queue arguments. */
	RTE_FLOW_PARSER_CMD_QUEUE_CREATE,
	RTE_FLOW_PARSER_CMD_QUEUE_DESTROY,
	RTE_FLOW_PARSER_CMD_QUEUE_FLOW_UPDATE_RESIZED,
	RTE_FLOW_PARSER_CMD_QUEUE_UPDATE,
	RTE_FLOW_PARSER_CMD_QUEUE_AGED,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION,

	/* Queue create arguments. */
	RTE_FLOW_PARSER_CMD_QUEUE_CREATE_POSTPONE,
	RTE_FLOW_PARSER_CMD_QUEUE_TEMPLATE_TABLE,
	RTE_FLOW_PARSER_CMD_QUEUE_PATTERN_TEMPLATE,
	RTE_FLOW_PARSER_CMD_QUEUE_ACTIONS_TEMPLATE,
	RTE_FLOW_PARSER_CMD_QUEUE_RULE_ID,

	/* Queue destroy arguments. */
	RTE_FLOW_PARSER_CMD_QUEUE_DESTROY_ID,
	RTE_FLOW_PARSER_CMD_QUEUE_DESTROY_POSTPONE,

	/* Queue update arguments. */
	RTE_FLOW_PARSER_CMD_QUEUE_UPDATE_ID,

	/* Queue indirect action arguments */
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_CREATE,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_LIST_CREATE,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_UPDATE,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_DESTROY,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_QUERY,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_QUERY_UPDATE,

	/* Queue indirect action create arguments */
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_CREATE_ID,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_INGRESS,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_EGRESS,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_TRANSFER,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_CREATE_POSTPONE,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_SPEC,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_LIST,

	/* Queue indirect action update arguments */
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_UPDATE_POSTPONE,

	/* Queue indirect action destroy arguments */
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_DESTROY_ID,
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_DESTROY_POSTPONE,

	/* Queue indirect action query arguments */
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_QUERY_POSTPONE,

	/* Queue indirect action query_update arguments */
	RTE_FLOW_PARSER_CMD_QUEUE_INDIRECT_ACTION_QU_MODE,

	/* Push arguments. */
	RTE_FLOW_PARSER_CMD_PUSH_QUEUE,

	/* Pull arguments. */
	RTE_FLOW_PARSER_CMD_PULL_QUEUE,

	/* Table arguments. */
	RTE_FLOW_PARSER_CMD_TABLE_CREATE,
	RTE_FLOW_PARSER_CMD_TABLE_DESTROY,
	RTE_FLOW_PARSER_CMD_TABLE_RESIZE,
	RTE_FLOW_PARSER_CMD_TABLE_RESIZE_COMPLETE,
	RTE_FLOW_PARSER_CMD_TABLE_CREATE_ID,
	RTE_FLOW_PARSER_CMD_TABLE_DESTROY_ID,
	RTE_FLOW_PARSER_CMD_TABLE_RESIZE_ID,
	RTE_FLOW_PARSER_CMD_TABLE_RESIZE_RULES_NUMBER,
	RTE_FLOW_PARSER_CMD_TABLE_INSERTION_TYPE,
	RTE_FLOW_PARSER_CMD_TABLE_INSERTION_TYPE_NAME,
	RTE_FLOW_PARSER_CMD_TABLE_HASH_FUNC,
	RTE_FLOW_PARSER_CMD_TABLE_HASH_FUNC_NAME,
	RTE_FLOW_PARSER_CMD_TABLE_GROUP,
	RTE_FLOW_PARSER_CMD_TABLE_PRIORITY,
	RTE_FLOW_PARSER_CMD_TABLE_INGRESS,
	RTE_FLOW_PARSER_CMD_TABLE_EGRESS,
	RTE_FLOW_PARSER_CMD_TABLE_TRANSFER,
	RTE_FLOW_PARSER_CMD_TABLE_TRANSFER_WIRE_ORIG,
	RTE_FLOW_PARSER_CMD_TABLE_TRANSFER_VPORT_ORIG,
	RTE_FLOW_PARSER_CMD_TABLE_RESIZABLE,
	RTE_FLOW_PARSER_CMD_TABLE_RULES_NUMBER,
	RTE_FLOW_PARSER_CMD_TABLE_PATTERN_TEMPLATE,
	RTE_FLOW_PARSER_CMD_TABLE_ACTIONS_TEMPLATE,

	/* Group arguments */
	RTE_FLOW_PARSER_CMD_GROUP_ID,
	RTE_FLOW_PARSER_CMD_GROUP_INGRESS,
	RTE_FLOW_PARSER_CMD_GROUP_EGRESS,
	RTE_FLOW_PARSER_CMD_GROUP_TRANSFER,
	RTE_FLOW_PARSER_CMD_GROUP_SET_MISS_ACTIONS,

	/* Hash calculation arguments. */
	RTE_FLOW_PARSER_CMD_HASH_CALC_TABLE,
	RTE_FLOW_PARSER_CMD_HASH_CALC_PATTERN_INDEX,
	RTE_FLOW_PARSER_CMD_HASH_CALC_PATTERN,
	RTE_FLOW_PARSER_CMD_HASH_CALC_ENCAP,
	RTE_FLOW_PARSER_CMD_HASH_CALC_DEST,
	RTE_FLOW_PARSER_CMD_ENCAP_HASH_FIELD_SRC_PORT,
	RTE_FLOW_PARSER_CMD_ENCAP_HASH_FIELD_GRE_FLOW_ID,

	/* Tunnel arguments. */
	RTE_FLOW_PARSER_CMD_TUNNEL_CREATE,
	RTE_FLOW_PARSER_CMD_TUNNEL_CREATE_TYPE,
	RTE_FLOW_PARSER_CMD_TUNNEL_LIST,
	RTE_FLOW_PARSER_CMD_TUNNEL_DESTROY,
	RTE_FLOW_PARSER_CMD_TUNNEL_DESTROY_ID,

	/* Destroy arguments. */
	RTE_FLOW_PARSER_CMD_DESTROY_RULE,
	RTE_FLOW_PARSER_CMD_DESTROY_IS_USER_ID,

	/* Query arguments. */
	RTE_FLOW_PARSER_CMD_QUERY_ACTION,
	RTE_FLOW_PARSER_CMD_QUERY_IS_USER_ID,

	/* List arguments. */
	RTE_FLOW_PARSER_CMD_LIST_GROUP,

	/* Destroy aged flow arguments. */
	RTE_FLOW_PARSER_CMD_AGED_DESTROY,

	/* Validate/create arguments. */
	RTE_FLOW_PARSER_CMD_VC_GROUP,
	RTE_FLOW_PARSER_CMD_VC_PRIORITY,
	RTE_FLOW_PARSER_CMD_VC_INGRESS,
	RTE_FLOW_PARSER_CMD_VC_EGRESS,
	RTE_FLOW_PARSER_CMD_VC_TRANSFER,
	RTE_FLOW_PARSER_CMD_VC_TUNNEL_SET,
	RTE_FLOW_PARSER_CMD_VC_TUNNEL_MATCH,
	RTE_FLOW_PARSER_CMD_VC_USER_ID,
	RTE_FLOW_PARSER_CMD_VC_IS_USER_ID,

	/* Dump arguments */
	RTE_FLOW_PARSER_CMD_DUMP_ALL,
	RTE_FLOW_PARSER_CMD_DUMP_ONE,
	RTE_FLOW_PARSER_CMD_DUMP_IS_USER_ID,

	/* Configure arguments */
	RTE_FLOW_PARSER_CMD_CONFIG_QUEUES_NUMBER,
	RTE_FLOW_PARSER_CMD_CONFIG_QUEUES_SIZE,
	RTE_FLOW_PARSER_CMD_CONFIG_COUNTERS_NUMBER,
	RTE_FLOW_PARSER_CMD_CONFIG_AGING_OBJECTS_NUMBER,
	RTE_FLOW_PARSER_CMD_CONFIG_METERS_NUMBER,
	RTE_FLOW_PARSER_CMD_CONFIG_CONN_TRACK_NUMBER,
	RTE_FLOW_PARSER_CMD_CONFIG_QUOTAS_NUMBER,
	RTE_FLOW_PARSER_CMD_CONFIG_FLAGS,
	RTE_FLOW_PARSER_CMD_CONFIG_HOST_PORT,

	/* Indirect action arguments */
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_CREATE,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_LIST_CREATE,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_FLOW_CONF_CREATE,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_UPDATE,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_DESTROY,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_QUERY,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_QUERY_UPDATE,

	/* Indirect action create arguments */
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_CREATE_ID,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_INGRESS,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_EGRESS,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_TRANSFER,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_SPEC,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_LIST,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_FLOW_CONF,

	/* Indirect action destroy arguments */
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_DESTROY_ID,

	/* Indirect action query-and-update arguments */
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_QU_MODE,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_QU_MODE_NAME,

	/* Validate/create pattern. */
	RTE_FLOW_PARSER_CMD_ITEM_PATTERN,
	RTE_FLOW_PARSER_CMD_ITEM_PARAM_IS,
	RTE_FLOW_PARSER_CMD_ITEM_PARAM_SPEC,
	RTE_FLOW_PARSER_CMD_ITEM_PARAM_LAST,
	RTE_FLOW_PARSER_CMD_ITEM_PARAM_MASK,
	RTE_FLOW_PARSER_CMD_ITEM_PARAM_PREFIX,
	RTE_FLOW_PARSER_CMD_ITEM_NEXT,
	RTE_FLOW_PARSER_CMD_ITEM_END,
	RTE_FLOW_PARSER_CMD_ITEM_VOID,
	RTE_FLOW_PARSER_CMD_ITEM_INVERT,
	RTE_FLOW_PARSER_CMD_ITEM_ANY,
	RTE_FLOW_PARSER_CMD_ITEM_ANY_NUM,
	RTE_FLOW_PARSER_CMD_ITEM_PORT_ID,
	RTE_FLOW_PARSER_CMD_ITEM_PORT_ID_ID,
	RTE_FLOW_PARSER_CMD_ITEM_MARK,
	RTE_FLOW_PARSER_CMD_ITEM_MARK_ID,
	RTE_FLOW_PARSER_CMD_ITEM_RAW,
	RTE_FLOW_PARSER_CMD_ITEM_RAW_RELATIVE,
	RTE_FLOW_PARSER_CMD_ITEM_RAW_SEARCH,
	RTE_FLOW_PARSER_CMD_ITEM_RAW_OFFSET,
	RTE_FLOW_PARSER_CMD_ITEM_RAW_LIMIT,
	RTE_FLOW_PARSER_CMD_ITEM_RAW_PATTERN,
	RTE_FLOW_PARSER_CMD_ITEM_RAW_PATTERN_HEX,
	RTE_FLOW_PARSER_CMD_ITEM_ETH,
	RTE_FLOW_PARSER_CMD_ITEM_ETH_DST,
	RTE_FLOW_PARSER_CMD_ITEM_ETH_SRC,
	RTE_FLOW_PARSER_CMD_ITEM_ETH_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_ETH_HAS_VLAN,
	RTE_FLOW_PARSER_CMD_ITEM_VLAN,
	RTE_FLOW_PARSER_CMD_ITEM_VLAN_TCI,
	RTE_FLOW_PARSER_CMD_ITEM_VLAN_PCP,
	RTE_FLOW_PARSER_CMD_ITEM_VLAN_DEI,
	RTE_FLOW_PARSER_CMD_ITEM_VLAN_VID,
	RTE_FLOW_PARSER_CMD_ITEM_VLAN_INNER_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_VLAN_HAS_MORE_VLAN,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_VER_IHL,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_TOS,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_LENGTH,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_ID,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_FRAGMENT_OFFSET,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_TTL,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_PROTO,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_SRC,
	RTE_FLOW_PARSER_CMD_ITEM_IPV4_DST,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_TC,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_FLOW,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_LEN,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_PROTO,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_HOP,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_SRC,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_DST,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_HAS_FRAG_EXT,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_ROUTING_EXT,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_ROUTING_EXT_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_ROUTING_EXT_NEXT_HDR,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_ROUTING_EXT_SEG_LEFT,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP_CODE,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP_IDENT,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP_SEQ,
	RTE_FLOW_PARSER_CMD_ITEM_UDP,
	RTE_FLOW_PARSER_CMD_ITEM_UDP_SRC,
	RTE_FLOW_PARSER_CMD_ITEM_UDP_DST,
	RTE_FLOW_PARSER_CMD_ITEM_TCP,
	RTE_FLOW_PARSER_CMD_ITEM_TCP_SRC,
	RTE_FLOW_PARSER_CMD_ITEM_TCP_DST,
	RTE_FLOW_PARSER_CMD_ITEM_TCP_FLAGS,
	RTE_FLOW_PARSER_CMD_ITEM_SCTP,
	RTE_FLOW_PARSER_CMD_ITEM_SCTP_SRC,
	RTE_FLOW_PARSER_CMD_ITEM_SCTP_DST,
	RTE_FLOW_PARSER_CMD_ITEM_SCTP_TAG,
	RTE_FLOW_PARSER_CMD_ITEM_SCTP_CKSUM,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_VNI,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FLAG_G,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FLAG_VER,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FLAG_I,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FLAG_P,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FLAG_B,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FLAG_O,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FLAG_D,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FLAG_A,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_GBP_ID,
	/* Used for "struct rte_vxlan_hdr", GPE Next protocol */
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_GPE_PROTO,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_FIRST_RSVD,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_SECND_RSVD,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_THIRD_RSVD,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_LAST_RSVD,
	RTE_FLOW_PARSER_CMD_ITEM_E_TAG,
	RTE_FLOW_PARSER_CMD_ITEM_E_TAG_GRP_ECID_B,
	RTE_FLOW_PARSER_CMD_ITEM_NVGRE,
	RTE_FLOW_PARSER_CMD_ITEM_NVGRE_TNI,
	RTE_FLOW_PARSER_CMD_ITEM_MPLS,
	RTE_FLOW_PARSER_CMD_ITEM_MPLS_LABEL,
	RTE_FLOW_PARSER_CMD_ITEM_MPLS_TC,
	RTE_FLOW_PARSER_CMD_ITEM_MPLS_S,
	RTE_FLOW_PARSER_CMD_ITEM_MPLS_TTL,
	RTE_FLOW_PARSER_CMD_ITEM_GRE,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_PROTO,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_C_RSVD0_VER,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_C_BIT,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_K_BIT,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_S_BIT,
	RTE_FLOW_PARSER_CMD_ITEM_FUZZY,
	RTE_FLOW_PARSER_CMD_ITEM_FUZZY_THRESH,
	RTE_FLOW_PARSER_CMD_ITEM_GTP,
	RTE_FLOW_PARSER_CMD_ITEM_GTP_FLAGS,
	RTE_FLOW_PARSER_CMD_ITEM_GTP_MSG_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_GTP_TEID,
	RTE_FLOW_PARSER_CMD_ITEM_GTPC,
	RTE_FLOW_PARSER_CMD_ITEM_GTPU,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE_VNI,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE_PROTO,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE_OPTLEN,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_GPE,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_GPE_VNI,
	/* Used for "struct rte_vxlan_gpe_hdr", deprecated, prefer ITEM_VXLAN_GPE_PROTO */
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_GPE_PROTO_IN_DEPRECATED_VXLAN_GPE_HDR,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_GPE_FLAGS,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_GPE_RSVD0,
	RTE_FLOW_PARSER_CMD_ITEM_VXLAN_GPE_RSVD1,
	RTE_FLOW_PARSER_CMD_ITEM_ARP_ETH_IPV4,
	RTE_FLOW_PARSER_CMD_ITEM_ARP_ETH_IPV4_SHA,
	RTE_FLOW_PARSER_CMD_ITEM_ARP_ETH_IPV4_SPA,
	RTE_FLOW_PARSER_CMD_ITEM_ARP_ETH_IPV4_THA,
	RTE_FLOW_PARSER_CMD_ITEM_ARP_ETH_IPV4_TPA,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_EXT,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_EXT_NEXT_HDR,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_FRAG_EXT,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_FRAG_EXT_NEXT_HDR,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_FRAG_EXT_FRAG_DATA,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_FRAG_EXT_ID,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_CODE,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ECHO_REQUEST,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ECHO_REQUEST_ID,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ECHO_REQUEST_SEQ,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ECHO_REPLY,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ECHO_REPLY_ID,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ECHO_REPLY_SEQ,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_NS,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_NS_TARGET_ADDR,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_NA,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_NA_TARGET_ADDR,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_OPT,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_OPT_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_OPT_SLA_ETH,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_OPT_SLA_ETH_SLA,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_OPT_TLA_ETH,
	RTE_FLOW_PARSER_CMD_ITEM_ICMP6_ND_OPT_TLA_ETH_TLA,
	RTE_FLOW_PARSER_CMD_ITEM_META,
	RTE_FLOW_PARSER_CMD_ITEM_META_DATA,
	RTE_FLOW_PARSER_CMD_ITEM_RANDOM,
	RTE_FLOW_PARSER_CMD_ITEM_RANDOM_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_KEY,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_KEY_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_OPTION,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_OPTION_CHECKSUM,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_OPTION_KEY,
	RTE_FLOW_PARSER_CMD_ITEM_GRE_OPTION_SEQUENCE,
	RTE_FLOW_PARSER_CMD_ITEM_GTP_PSC,
	RTE_FLOW_PARSER_CMD_ITEM_GTP_PSC_QFI,
	RTE_FLOW_PARSER_CMD_ITEM_GTP_PSC_PDU_T,
	RTE_FLOW_PARSER_CMD_ITEM_PPPOES,
	RTE_FLOW_PARSER_CMD_ITEM_PPPOED,
	RTE_FLOW_PARSER_CMD_ITEM_PPPOE_SEID,
	RTE_FLOW_PARSER_CMD_ITEM_PPPOE_PROTO_ID,
	RTE_FLOW_PARSER_CMD_ITEM_HIGIG2,
	RTE_FLOW_PARSER_CMD_ITEM_HIGIG2_CLASSIFICATION,
	RTE_FLOW_PARSER_CMD_ITEM_HIGIG2_VID,
	RTE_FLOW_PARSER_CMD_ITEM_TAG,
	RTE_FLOW_PARSER_CMD_ITEM_TAG_DATA,
	RTE_FLOW_PARSER_CMD_ITEM_TAG_INDEX,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV3OIP,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV3OIP_SESSION_ID,
	RTE_FLOW_PARSER_CMD_ITEM_ESP,
	RTE_FLOW_PARSER_CMD_ITEM_ESP_SPI,
	RTE_FLOW_PARSER_CMD_ITEM_AH,
	RTE_FLOW_PARSER_CMD_ITEM_AH_SPI,
	RTE_FLOW_PARSER_CMD_ITEM_PFCP,
	RTE_FLOW_PARSER_CMD_ITEM_PFCP_S_FIELD,
	RTE_FLOW_PARSER_CMD_ITEM_PFCP_SEID,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI_COMMON,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI_COMMON_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI_COMMON_TYPE_IQ_DATA,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI_COMMON_TYPE_RTC_CTRL,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI_COMMON_TYPE_DLY_MSR,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI_MSG_IQ_DATA_PCID,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI_MSG_RTC_CTRL_RTCID,
	RTE_FLOW_PARSER_CMD_ITEM_ECPRI_MSG_DLY_MSR_MSRID,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE_OPT,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE_OPT_CLASS,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE_OPT_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE_OPT_LENGTH,
	RTE_FLOW_PARSER_CMD_ITEM_GENEVE_OPT_DATA,
	RTE_FLOW_PARSER_CMD_ITEM_INTEGRITY,
	RTE_FLOW_PARSER_CMD_ITEM_INTEGRITY_LEVEL,
	RTE_FLOW_PARSER_CMD_ITEM_INTEGRITY_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_CONNTRACK,
	RTE_FLOW_PARSER_CMD_ITEM_POL_PORT,
	RTE_FLOW_PARSER_CMD_ITEM_POL_METER,
	RTE_FLOW_PARSER_CMD_ITEM_POL_POLICY,
	RTE_FLOW_PARSER_CMD_ITEM_PORT_REPRESENTOR,
	RTE_FLOW_PARSER_CMD_ITEM_PORT_REPRESENTOR_PORT_ID,
	RTE_FLOW_PARSER_CMD_ITEM_REPRESENTED_PORT,
	RTE_FLOW_PARSER_CMD_ITEM_REPRESENTED_PORT_ETHDEV_PORT_ID,
	RTE_FLOW_PARSER_CMD_ITEM_FLEX,
	RTE_FLOW_PARSER_CMD_ITEM_FLEX_ITEM_HANDLE,
	RTE_FLOW_PARSER_CMD_ITEM_FLEX_PATTERN_HANDLE,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_TYPE_DATA,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_TYPE_DATA_L,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_TYPE_DATA_S,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_TYPE_DATA_O,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_TYPE_DATA_L_S,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_TYPE_CTRL,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_TUNNEL_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_SESSION_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_L_LENGTH,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_L_TUNNEL_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_L_SESSION_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_S_TUNNEL_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_S_SESSION_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_S_NS,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_S_NR,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_O_TUNNEL_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_O_SESSION_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_O_OFFSET,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_L_S_LENGTH,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_L_S_TUNNEL_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_L_S_SESSION_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_L_S_NS,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_DATA_L_S_NR,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_CTRL_LENGTH,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_CTRL_TUNNEL_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_CTRL_SESSION_ID,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_CTRL_NS,
	RTE_FLOW_PARSER_CMD_ITEM_L2TPV2_MSG_CTRL_NR,
	RTE_FLOW_PARSER_CMD_ITEM_PPP,
	RTE_FLOW_PARSER_CMD_ITEM_PPP_ADDR,
	RTE_FLOW_PARSER_CMD_ITEM_PPP_CTRL,
	RTE_FLOW_PARSER_CMD_ITEM_PPP_PROTO_ID,
	RTE_FLOW_PARSER_CMD_ITEM_METER,
	RTE_FLOW_PARSER_CMD_ITEM_METER_COLOR,
	RTE_FLOW_PARSER_CMD_ITEM_QUOTA,
	RTE_FLOW_PARSER_CMD_ITEM_QUOTA_STATE,
	RTE_FLOW_PARSER_CMD_ITEM_QUOTA_STATE_NAME,
	RTE_FLOW_PARSER_CMD_ITEM_AGGR_AFFINITY,
	RTE_FLOW_PARSER_CMD_ITEM_AGGR_AFFINITY_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_TX_QUEUE,
	RTE_FLOW_PARSER_CMD_ITEM_TX_QUEUE_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_IB_BTH,
	RTE_FLOW_PARSER_CMD_ITEM_IB_BTH_OPCODE,
	RTE_FLOW_PARSER_CMD_ITEM_IB_BTH_PKEY,
	RTE_FLOW_PARSER_CMD_ITEM_IB_BTH_DST_QPN,
	RTE_FLOW_PARSER_CMD_ITEM_IB_BTH_PSN,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_PUSH_REMOVE_EXT,
	RTE_FLOW_PARSER_CMD_ITEM_IPV6_PUSH_REMOVE_EXT_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_PTYPE,
	RTE_FLOW_PARSER_CMD_ITEM_PTYPE_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_NSH,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_OP,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_OP_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_A_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_A_TYPE_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_A_LEVEL,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_A_LEVEL_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_A_TAG_INDEX,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_A_TYPE_ID,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_A_CLASS_ID,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_A_OFFSET,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_TYPE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_TYPE_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_LEVEL,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_LEVEL_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_TAG_INDEX,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_TYPE_ID,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_CLASS_ID,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_OFFSET,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_VALUE,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_B_POINTER,
	RTE_FLOW_PARSER_CMD_ITEM_COMPARE_FIELD_WIDTH,

	/* Validate/create actions. */
	RTE_FLOW_PARSER_CMD_ACTIONS,
	RTE_FLOW_PARSER_CMD_ACTION_NEXT,
	RTE_FLOW_PARSER_CMD_ACTION_END,
	RTE_FLOW_PARSER_CMD_ACTION_VOID,
	RTE_FLOW_PARSER_CMD_ACTION_PASSTHRU,
	RTE_FLOW_PARSER_CMD_ACTION_SKIP_CMAN,
	RTE_FLOW_PARSER_CMD_ACTION_JUMP,
	RTE_FLOW_PARSER_CMD_ACTION_JUMP_GROUP,
	RTE_FLOW_PARSER_CMD_ACTION_MARK,
	RTE_FLOW_PARSER_CMD_ACTION_MARK_ID,
	RTE_FLOW_PARSER_CMD_ACTION_FLAG,
	RTE_FLOW_PARSER_CMD_ACTION_QUEUE,
	RTE_FLOW_PARSER_CMD_ACTION_QUEUE_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_DROP,
	RTE_FLOW_PARSER_CMD_ACTION_COUNT,
	RTE_FLOW_PARSER_CMD_ACTION_COUNT_ID,
	RTE_FLOW_PARSER_CMD_ACTION_RSS,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_FUNC,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_LEVEL,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_FUNC_DEFAULT,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_FUNC_TOEPLITZ,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_FUNC_SIMPLE_XOR,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_FUNC_SYMMETRIC_TOEPLITZ,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_TYPES,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_TYPE,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_KEY,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_KEY_LEN,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_QUEUES,
	RTE_FLOW_PARSER_CMD_ACTION_RSS_QUEUE,
	RTE_FLOW_PARSER_CMD_ACTION_PF,
	RTE_FLOW_PARSER_CMD_ACTION_VF,
	RTE_FLOW_PARSER_CMD_ACTION_VF_ORIGINAL,
	RTE_FLOW_PARSER_CMD_ACTION_VF_ID,
	RTE_FLOW_PARSER_CMD_ACTION_PORT_ID,
	RTE_FLOW_PARSER_CMD_ACTION_PORT_ID_ORIGINAL,
	RTE_FLOW_PARSER_CMD_ACTION_PORT_ID_ID,
	RTE_FLOW_PARSER_CMD_ACTION_METER,
	RTE_FLOW_PARSER_CMD_ACTION_METER_COLOR,
	RTE_FLOW_PARSER_CMD_ACTION_METER_COLOR_TYPE,
	RTE_FLOW_PARSER_CMD_ACTION_METER_COLOR_GREEN,
	RTE_FLOW_PARSER_CMD_ACTION_METER_COLOR_YELLOW,
	RTE_FLOW_PARSER_CMD_ACTION_METER_COLOR_RED,
	RTE_FLOW_PARSER_CMD_ACTION_METER_ID,
	RTE_FLOW_PARSER_CMD_ACTION_METER_MARK,
	RTE_FLOW_PARSER_CMD_ACTION_METER_MARK_CONF,
	RTE_FLOW_PARSER_CMD_ACTION_METER_MARK_CONF_COLOR,
	RTE_FLOW_PARSER_CMD_ACTION_METER_PROFILE,
	RTE_FLOW_PARSER_CMD_ACTION_METER_PROFILE_ID2PTR,
	RTE_FLOW_PARSER_CMD_ACTION_METER_POLICY,
	RTE_FLOW_PARSER_CMD_ACTION_METER_POLICY_ID2PTR,
	RTE_FLOW_PARSER_CMD_ACTION_METER_COLOR_MODE,
	RTE_FLOW_PARSER_CMD_ACTION_METER_STATE,
	RTE_FLOW_PARSER_CMD_ACTION_OF_DEC_NW_TTL,
	RTE_FLOW_PARSER_CMD_ACTION_OF_POP_VLAN,
	RTE_FLOW_PARSER_CMD_ACTION_OF_PUSH_VLAN,
	RTE_FLOW_PARSER_CMD_ACTION_OF_PUSH_VLAN_ETHERTYPE,
	RTE_FLOW_PARSER_CMD_ACTION_OF_SET_VLAN_VID,
	RTE_FLOW_PARSER_CMD_ACTION_OF_SET_VLAN_VID_VLAN_VID,
	RTE_FLOW_PARSER_CMD_ACTION_OF_SET_VLAN_PCP,
	RTE_FLOW_PARSER_CMD_ACTION_OF_SET_VLAN_PCP_VLAN_PCP,
	RTE_FLOW_PARSER_CMD_ACTION_OF_POP_MPLS,
	RTE_FLOW_PARSER_CMD_ACTION_OF_POP_MPLS_ETHERTYPE,
	RTE_FLOW_PARSER_CMD_ACTION_OF_PUSH_MPLS,
	RTE_FLOW_PARSER_CMD_ACTION_OF_PUSH_MPLS_ETHERTYPE,
	RTE_FLOW_PARSER_CMD_ACTION_VXLAN_ENCAP,
	RTE_FLOW_PARSER_CMD_ACTION_VXLAN_DECAP,
	RTE_FLOW_PARSER_CMD_ACTION_NVGRE_ENCAP,
	RTE_FLOW_PARSER_CMD_ACTION_NVGRE_DECAP,
	RTE_FLOW_PARSER_CMD_ACTION_L2_ENCAP,
	RTE_FLOW_PARSER_CMD_ACTION_L2_DECAP,
	RTE_FLOW_PARSER_CMD_ACTION_MPLSOGRE_ENCAP,
	RTE_FLOW_PARSER_CMD_ACTION_MPLSOGRE_DECAP,
	RTE_FLOW_PARSER_CMD_ACTION_MPLSOUDP_ENCAP,
	RTE_FLOW_PARSER_CMD_ACTION_MPLSOUDP_DECAP,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV4_SRC,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV4_SRC_IPV4_SRC,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV4_DST,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV4_DST_IPV4_DST,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV6_SRC,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV6_SRC_IPV6_SRC,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV6_DST,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV6_DST_IPV6_DST,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TP_SRC,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TP_SRC_TP_SRC,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TP_DST,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TP_DST_TP_DST,
	RTE_FLOW_PARSER_CMD_ACTION_MAC_SWAP,
	RTE_FLOW_PARSER_CMD_ACTION_DEC_TTL,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TTL,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TTL_TTL,
	RTE_FLOW_PARSER_CMD_ACTION_SET_MAC_SRC,
	RTE_FLOW_PARSER_CMD_ACTION_SET_MAC_SRC_MAC_SRC,
	RTE_FLOW_PARSER_CMD_ACTION_SET_MAC_DST,
	RTE_FLOW_PARSER_CMD_ACTION_SET_MAC_DST_MAC_DST,
	RTE_FLOW_PARSER_CMD_ACTION_INC_TCP_SEQ,
	RTE_FLOW_PARSER_CMD_ACTION_INC_TCP_SEQ_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_DEC_TCP_SEQ,
	RTE_FLOW_PARSER_CMD_ACTION_DEC_TCP_SEQ_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_INC_TCP_ACK,
	RTE_FLOW_PARSER_CMD_ACTION_INC_TCP_ACK_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_DEC_TCP_ACK,
	RTE_FLOW_PARSER_CMD_ACTION_DEC_TCP_ACK_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_RAW_ENCAP,
	RTE_FLOW_PARSER_CMD_ACTION_RAW_DECAP,
	RTE_FLOW_PARSER_CMD_ACTION_RAW_ENCAP_SIZE,
	RTE_FLOW_PARSER_CMD_ACTION_RAW_ENCAP_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_RAW_ENCAP_INDEX_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_RAW_DECAP_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_RAW_DECAP_INDEX_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TAG,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TAG_DATA,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TAG_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_SET_TAG_MASK,
	RTE_FLOW_PARSER_CMD_ACTION_SET_META,
	RTE_FLOW_PARSER_CMD_ACTION_SET_META_DATA,
	RTE_FLOW_PARSER_CMD_ACTION_SET_META_MASK,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV4_DSCP,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV4_DSCP_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV6_DSCP,
	RTE_FLOW_PARSER_CMD_ACTION_SET_IPV6_DSCP_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_AGE,
	RTE_FLOW_PARSER_CMD_ACTION_AGE_TIMEOUT,
	RTE_FLOW_PARSER_CMD_ACTION_AGE_UPDATE,
	RTE_FLOW_PARSER_CMD_ACTION_AGE_UPDATE_TIMEOUT,
	RTE_FLOW_PARSER_CMD_ACTION_AGE_UPDATE_TOUCH,
	RTE_FLOW_PARSER_CMD_ACTION_SAMPLE,
	RTE_FLOW_PARSER_CMD_ACTION_SAMPLE_RATIO,
	RTE_FLOW_PARSER_CMD_ACTION_SAMPLE_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_SAMPLE_INDEX_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_INDIRECT,
	RTE_FLOW_PARSER_CMD_ACTION_INDIRECT_LIST,
	RTE_FLOW_PARSER_CMD_ACTION_INDIRECT_LIST_HANDLE,
	RTE_FLOW_PARSER_CMD_ACTION_INDIRECT_LIST_CONF,
	RTE_FLOW_PARSER_CMD_INDIRECT_LIST_ACTION_ID2PTR_HANDLE,
	RTE_FLOW_PARSER_CMD_INDIRECT_LIST_ACTION_ID2PTR_CONF,
	RTE_FLOW_PARSER_CMD_ACTION_SHARED_INDIRECT,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_PORT,
	RTE_FLOW_PARSER_CMD_INDIRECT_ACTION_ID2PTR,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_OP,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_OP_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_DST_TYPE,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_DST_TYPE_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_DST_LEVEL,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_DST_LEVEL_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_DST_TAG_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_DST_TYPE_ID,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_DST_CLASS_ID,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_DST_OFFSET,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_TYPE,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_TYPE_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_LEVEL,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_LEVEL_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_TAG_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_TYPE_ID,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_CLASS_ID,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_OFFSET,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_SRC_POINTER,
	RTE_FLOW_PARSER_CMD_ACTION_MODIFY_FIELD_WIDTH,
	RTE_FLOW_PARSER_CMD_ACTION_CONNTRACK,
	RTE_FLOW_PARSER_CMD_ACTION_CONNTRACK_UPDATE,
	RTE_FLOW_PARSER_CMD_ACTION_CONNTRACK_UPDATE_DIR,
	RTE_FLOW_PARSER_CMD_ACTION_CONNTRACK_UPDATE_CTX,
	RTE_FLOW_PARSER_CMD_ACTION_POL_G,
	RTE_FLOW_PARSER_CMD_ACTION_POL_Y,
	RTE_FLOW_PARSER_CMD_ACTION_POL_R,
	RTE_FLOW_PARSER_CMD_ACTION_PORT_REPRESENTOR,
	RTE_FLOW_PARSER_CMD_ACTION_PORT_REPRESENTOR_PORT_ID,
	RTE_FLOW_PARSER_CMD_ACTION_REPRESENTED_PORT,
	RTE_FLOW_PARSER_CMD_ACTION_REPRESENTED_PORT_ETHDEV_PORT_ID,
	RTE_FLOW_PARSER_CMD_ACTION_SEND_TO_KERNEL,
	RTE_FLOW_PARSER_CMD_ACTION_QUOTA_CREATE,
	RTE_FLOW_PARSER_CMD_ACTION_QUOTA_CREATE_LIMIT,
	RTE_FLOW_PARSER_CMD_ACTION_QUOTA_CREATE_MODE,
	RTE_FLOW_PARSER_CMD_ACTION_QUOTA_CREATE_MODE_NAME,
	RTE_FLOW_PARSER_CMD_ACTION_QUOTA_QU,
	RTE_FLOW_PARSER_CMD_ACTION_QUOTA_QU_LIMIT,
	RTE_FLOW_PARSER_CMD_ACTION_QUOTA_QU_UPDATE_OP,
	RTE_FLOW_PARSER_CMD_ACTION_QUOTA_QU_UPDATE_OP_NAME,
	RTE_FLOW_PARSER_CMD_ACTION_IPV6_EXT_REMOVE,
	RTE_FLOW_PARSER_CMD_ACTION_IPV6_EXT_REMOVE_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_IPV6_EXT_REMOVE_INDEX_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_IPV6_EXT_PUSH,
	RTE_FLOW_PARSER_CMD_ACTION_IPV6_EXT_PUSH_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_IPV6_EXT_PUSH_INDEX_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_NAT64,
	RTE_FLOW_PARSER_CMD_ACTION_NAT64_MODE,
	RTE_FLOW_PARSER_CMD_ACTION_JUMP_TO_TABLE_INDEX,
	RTE_FLOW_PARSER_CMD_ACTION_JUMP_TO_TABLE_INDEX_TABLE,
	RTE_FLOW_PARSER_CMD_ACTION_JUMP_TO_TABLE_INDEX_TABLE_VALUE,
	RTE_FLOW_PARSER_CMD_ACTION_JUMP_TO_TABLE_INDEX_INDEX,
};

/** Parser output buffer layout expected by rte_flow_parser_parse(). */
struct rte_flow_parser_output {
	enum rte_flow_parser_command_index command; /**< Flow command. */
	uint16_t port; /**< Affected port ID. */
	uint16_t queue; /** Async queue ID. */
	bool postpone; /** Postpone async operation */
	union {
		struct {
			struct rte_flow_port_attr port_attr;
			uint32_t nb_queue;
			struct rte_flow_queue_attr queue_attr;
		} configure; /**< Configuration arguments. */
		struct {
			uint32_t *template_id;
			uint32_t template_id_n;
		} templ_destroy; /**< Template destroy arguments. */
		struct {
			uint32_t id;
			struct rte_flow_template_table_attr attr;
			uint32_t *pat_templ_id;
			uint32_t pat_templ_id_n;
			uint32_t *act_templ_id;
			uint32_t act_templ_id_n;
		} table; /**< Table arguments. */
		struct {
			uint32_t *table_id;
			uint32_t table_id_n;
		} table_destroy; /**< Template destroy arguments. */
		struct {
			uint32_t *action_id;
			uint32_t action_id_n;
		} ia_destroy; /**< Indirect action destroy arguments. */
		struct {
			uint32_t action_id;
			enum rte_flow_query_update_mode qu_mode;
		} ia; /* Indirect action query arguments */
		struct {
			uint32_t table_id;
			uint32_t pat_templ_id;
			uint32_t rule_id;
			uint32_t act_templ_id;
			struct rte_flow_attr attr;
			struct rte_flow_parser_tunnel_ops tunnel_ops;
			uintptr_t user_id;
			struct rte_flow_item *pattern;
			struct rte_flow_action *actions;
			struct rte_flow_action *masks;
			uint32_t pattern_n;
			uint32_t actions_n;
			uint8_t *data;
			enum rte_flow_encap_hash_field field;
			uint8_t encap_hash;
			bool is_user_id;
		} vc; /**< Validate/create arguments. */
		struct {
			uint64_t *rule;
			uint64_t rule_n;
			bool is_user_id;
		} destroy; /**< Destroy arguments. */
		struct {
			char file[128];
			bool mode;
			uint64_t rule;
			bool is_user_id;
		} dump; /**< Dump arguments. */
		struct {
			uint64_t rule;
			struct rte_flow_action action;
			bool is_user_id;
		} query; /**< Query arguments. */
		struct {
			uint32_t *group;
			uint32_t group_n;
		} list; /**< List arguments. */
		struct {
			int set;
		} isolate; /**< Isolated mode arguments. */
		struct {
			int destroy;
		} aged; /**< Aged arguments. */
		struct {
			uint32_t policy_id;
		} policy;/**< Policy arguments. */
		struct {
			uint16_t token;
			uintptr_t uintptr;
			char filename[128];
		} flex; /**< Flex arguments*/
	} args; /**< Command arguments. */
};

/**
 * Query hooks: the parser consults these to validate IDs and fetch cached
 * objects for completions or rule composition.
 */
struct rte_flow_parser_ops_query {
	int (*port_validate)(uint16_t port_id);
	uint16_t (*flow_rule_count)(uint16_t port_id);
	int (*flow_rule_id_get)(uint16_t port_id, unsigned int index,
			      uint64_t *rule_id);
	uint16_t (*pattern_template_count)(uint16_t port_id);
	int (*pattern_template_id_get)(uint16_t port_id, unsigned int index,
				     uint32_t *template_id);
	uint16_t (*actions_template_count)(uint16_t port_id);
	int (*actions_template_id_get)(uint16_t port_id, unsigned int index,
				       uint32_t *template_id);
	uint16_t (*table_count)(uint16_t port_id);
	int (*table_id_get)(uint16_t port_id, unsigned int index,
			    uint32_t *table_id);
	uint16_t (*queue_count)(uint16_t port_id);
	uint16_t (*rss_queue_count)(uint16_t port_id);
	struct rte_flow_template_table *(*table_get)(uint16_t port_id,
						    uint32_t table_id);
	struct rte_flow_action_handle *(*action_handle_get)(uint16_t port_id,
						       uint32_t action_id);
	struct rte_flow_meter_profile *(*meter_profile_get)(uint16_t port_id,
						      uint32_t profile_id);
	struct rte_flow_meter_policy *(*meter_policy_get)(uint16_t port_id,
						     uint32_t policy_id);
	struct rte_flow_item_flex_handle *(*flex_handle_get)(uint16_t port_id,
						     uint16_t flex_id);
	uint16_t (*verbose_level_get)(void);
	int (*flex_pattern_get)(uint16_t pattern_id,
			       const struct rte_flow_item_flex **spec,
			       const struct rte_flow_item_flex **mask);
};

/**
 * Command hooks: executed when the parser accepts a command. Applications
 * should implement the callbacks they need; unused callbacks may be NULL.
 */
struct rte_flow_parser_ops_command {
	int (*flow_get_info)(uint16_t port_id);
	int (*flow_configure)(uint16_t port_id,
			const struct rte_flow_port_attr *port_attr,
			uint16_t nb_queue,
			const struct rte_flow_queue_attr *queue_attr);
	int (*flow_pattern_template_create)(uint16_t port_id, uint32_t id,
				 const struct rte_flow_pattern_template_attr *attr,
				 const struct rte_flow_item pattern[]);
	int (*flow_pattern_template_destroy)(uint16_t port_id,
				 uint32_t nb_id, const uint32_t id[]);
	int (*flow_actions_template_create)(uint16_t port_id, uint32_t id,
				 const struct rte_flow_actions_template_attr *attr,
				 const struct rte_flow_action actions[],
				 const struct rte_flow_action masks[]);
	int (*flow_actions_template_destroy)(uint16_t port_id,
				 uint32_t nb_id, const uint32_t id[]);
	int (*flow_template_table_create)(uint16_t port_id, uint32_t table_id,
			 const struct rte_flow_template_table_attr *attr,
			 uint32_t nb_pattern, uint32_t pattern_id[],
			 uint32_t nb_action, uint32_t action_id[]);
	int (*flow_template_table_destroy)(uint16_t port_id, uint32_t nb_id,
			 const uint32_t id[]);
	int (*flow_template_table_resize_complete)(uint16_t port_id,
			uint32_t table_id);
	int (*queue_group_set_miss_actions)(uint16_t port_id,
			const struct rte_flow_attr *attr,
			const struct rte_flow_action actions[]);
	int (*flow_template_table_resize)(uint16_t port_id, uint32_t table_id,
			 uint32_t nb_rules);
	int (*queue_flow_create)(uint16_t port_id, uint16_t queue,
			  bool postpone, uint32_t table_id,
			  uint32_t rule_id, uint32_t pattern_template_id,
			  uint32_t action_template_id,
			  const struct rte_flow_item pattern[],
			  const struct rte_flow_action actions[]);
	int (*queue_flow_destroy)(uint16_t port_id, uint16_t queue,
			   bool postpone, uint32_t nb_rule,
			   const uint64_t rule[]);
	int (*queue_flow_update_resized)(uint16_t port_id, uint16_t queue,
			 bool postpone, uint32_t rule_id);
	int (*queue_flow_update)(uint16_t port_id, uint16_t queue,
			 bool postpone, uint32_t rule_id,
			 uint32_t action_template_id,
			 const struct rte_flow_action actions[]);
	int (*queue_flow_push)(uint16_t port_id, uint16_t queue);
	int (*queue_flow_pull)(uint16_t port_id, uint16_t queue);
	int (*flow_hash_calc)(uint16_t port_id, uint32_t table_id,
		    uint8_t pattern_template_id,
		    const struct rte_flow_item pattern[]);
	int (*flow_hash_calc_encap)(uint16_t port_id,
		       enum rte_flow_encap_hash_field field,
		       const struct rte_flow_item pattern[]);
	void (*queue_flow_aged)(uint16_t port_id, uint32_t queue,
		    uint8_t destroy);
	int (*queue_action_handle_create)(uint16_t port_id, uint32_t queue,
		     bool postpone, uint32_t group,
		     bool is_list, const struct rte_flow_indir_action_conf *conf,
		     const struct rte_flow_action actions[]);
	int (*queue_action_handle_destroy)(uint16_t port_id, uint32_t queue,
		     bool postpone, uint32_t nb_id, const uint32_t id[]);
	int (*queue_action_handle_update)(uint16_t port_id, uint32_t queue,
		     bool postpone, uint32_t group,
		     const struct rte_flow_action actions[]);
	int (*queue_action_handle_query)(uint16_t port_id, uint32_t queue,
		     bool postpone, uint32_t action_id);
	void (*queue_action_handle_query_update)(uint16_t port_id,
		     uint32_t queue, bool postpone, uint32_t action_id,
		     enum rte_flow_query_update_mode qu_mode,
		     const struct rte_flow_action actions[]);
	int (*action_handle_create)(uint16_t port_id, uint32_t group,
		    bool is_list, const struct rte_flow_indir_action_conf *conf,
		    const struct rte_flow_action actions[]);
	int (*action_handle_destroy)(uint16_t port_id, uint32_t nb_id,
		    const uint32_t id[]);
	int (*action_handle_update)(uint16_t port_id, uint32_t group,
		    const struct rte_flow_action actions[]);
	int (*action_handle_query)(uint16_t port_id, uint32_t action_id);
	void (*action_handle_query_update)(uint16_t port_id, uint32_t action_id,
		    enum rte_flow_query_update_mode qu_mode,
		    const struct rte_flow_action actions[]);
	int (*flow_validate)(uint16_t port_id, const struct rte_flow_attr *attr,
		  const struct rte_flow_item pattern[],
		  const struct rte_flow_action actions[],
		  const struct rte_flow_parser_tunnel_ops *ops);
	int (*flow_create)(uint16_t port_id, const struct rte_flow_attr *attr,
		 const struct rte_flow_item pattern[],
		 const struct rte_flow_action actions[],
		 const struct rte_flow_parser_tunnel_ops *ops, uintptr_t user_id);
	int (*flow_destroy)(uint16_t port_id, uint32_t nb_rule,
		 const uint64_t rule[], bool is_user_id);
	int (*flow_update)(uint16_t port_id, uint32_t rule_id,
		 const struct rte_flow_action actions[], bool is_user_id);
	int (*flow_flush)(uint16_t port_id);
	int (*flow_dump)(uint16_t port_id, bool all, uint64_t rule,
		 const char *file, bool is_user_id);
	int (*flow_query)(uint16_t port_id, uint64_t rule,
		 const struct rte_flow_action *action, bool is_user_id);
	void (*flow_list)(uint16_t port_id, uint32_t group_n,
		 const uint32_t group[]);
	int (*flow_isolate)(uint16_t port_id, int set);
	void (*flow_aged)(uint16_t port_id, int destroy);
	void (*flow_tunnel_create)(uint16_t port_id,
		 const struct rte_flow_parser_tunnel_ops *ops);
	void (*flow_tunnel_destroy)(uint16_t port_id, uint32_t id);
	void (*flow_tunnel_list)(uint16_t port_id);
	int (*meter_policy_add)(uint16_t port_id, uint32_t policy_id,
		 const struct rte_flow_action actions[]);
	void (*flex_item_create)(uint16_t port_id, uint16_t flex_id,
		 const char *filename);
	void (*flex_item_destroy)(uint16_t port_id, uint16_t flex_id);
};

struct rte_flow_parser_ops {
	const struct rte_flow_parser_ops_query *query;
	const struct rte_flow_parser_ops_command *command;
};

/* rte_flow_parser_init() is declared in rte_flow_parser.h */

/**
 * Register cmdline instances so the parser can drive dynamic tokens and
 * update help strings. Applications should pass their cmdline instances for
 * the flow and set commands.
 */
__rte_experimental
void rte_flow_parser_cmdline_register(cmdline_parse_inst_t *flow,
				      cmdline_parse_inst_t *set_raw);

__rte_experimental
void rte_flow_parser_cmd_flow_tok(cmdline_parse_token_hdr_t **hdr,
				  cmdline_parse_token_hdr_t **hdr_inst);

__rte_experimental
void rte_flow_parser_cmd_set_raw_tok(cmdline_parse_token_hdr_t **hdr,
				     cmdline_parse_token_hdr_t **hdr_inst);

__rte_experimental
void rte_flow_parser_cmd_flow_dispatch(struct rte_flow_parser_output *out);

__rte_experimental
void rte_flow_parser_cmd_set_raw_dispatch(struct rte_flow_parser_output *out);

/**
 * Parse a flow CLI string.
 *
 * @param src
 *   NUL-terminated string containing one or more flow commands.
 * @param result
 *   Output buffer where the parsed result is stored.
 * @param result_size
 *   Size of the output buffer in bytes.
 * @return
 *   0 on success, -EINVAL on syntax error, -ENOBUFS if result_size is too
 *   small, or a negative errno-style value on other errors.
 */
__rte_experimental
int rte_flow_parser_parse(const char *src,
			 struct rte_flow_parser_output *result,
			 size_t result_size);

/**
 * Parse and execute a flow CLI string using installed command ops.
 *
 * @param src
 *   NUL-terminated string containing one or more flow commands.
 * @return
 *   0 on success, -EINVAL on syntax error, or a negative errno-style value
 *   on other errors.
 */
__rte_experimental
int rte_flow_parser_run(const char *src);

#ifdef __cplusplus
}
#endif

#endif /* _RTE_FLOW_PARSER_PRIVATE_H_ */
