# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020 Mellanox Technologies, Ltd

include $(RTE_SDK)/mk/rte.vars.mk

APP = dpdk-test-regex

CFLAGS += -O3
CFLAGS += $(WERROR_FLAGS)

SRCS-y := main.c

include $(RTE_SDK)/mk/rte.app.mk
