# SPDX-License-Identifier: BSD-3-Clause

# Optional Fields:
#   All fields are optional, uncomment a test suite to run it with a specific configuration.

# Define the custom test suite configurations
hello_world:
  msg: A custom hello world to you!
# single_core_forward_perf:
#   test_parameters: # Add frame size / descriptor count combinations as needed
#     - frame_size: 64
#       num_descriptors: 512
#       expected_mpps: 1.0 # Set millions of packets per second according to your devices expected throughput for this given frame size / descriptor count
#     - frame_size: 64
#       num_descriptors: 1024
#       expected_mpps: 1.0
#     - frame_size: 512
#       num_descriptors: 1024
#       expected_mpps: 1.0
#   delta_tolerance: 0.05
# pmd_rss:
#   NUM_QUEUES: 4
#   ACTUAL_KEY_SIZE: 52
#   ACTUAL_RETA_SIZE: 512
# cryptodev_throughput:
#   delta_tolerance: 0.05
#   throughput_test_parameters:
#     snow3g_uea2_snow3g_uia2: # Add the name of the test suite you would like to run
#      - buff_size: 64
#        Gbps: 2.0 # Set gigabits per second according to your devices throughput for this given buffer size
#      - buff_size: 512
#        Gbps: 20.0
