/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2014-2021 Broadcom
 * All rights reserved.
 */

/* date: Mon Nov 23 17:33:02 2020 */

#include "ulp_template_db_enum.h"
#include "ulp_template_db_field.h"
#include "ulp_template_struct.h"
#include "ulp_template_db_tbl.h"

/* Define the template structures */
/*
 * Classification signature table:
 * maps hash id to ulp_class_match_list[] index
 */
uint16_t ulp_class_sig_tbl[BNXT_ULP_CLASS_SIG_TBL_MAX_SZ] = {
	[BNXT_ULP_CLASS_HID_00fc] = 1,
	[BNXT_ULP_CLASS_HID_0046] = 2,
	[BNXT_ULP_CLASS_HID_0056] = 3,
	[BNXT_ULP_CLASS_HID_00b8] = 4,
	[BNXT_ULP_CLASS_HID_0041] = 5,
	[BNXT_ULP_CLASS_HID_00ab] = 6,
	[BNXT_ULP_CLASS_HID_0053] = 7,
	[BNXT_ULP_CLASS_HID_00a5] = 8,
	[BNXT_ULP_CLASS_HID_0069] = 9,
	[BNXT_ULP_CLASS_HID_009d] = 10,
	[BNXT_ULP_CLASS_HID_0005] = 11,
	[BNXT_ULP_CLASS_HID_006f] = 12,
	[BNXT_ULP_CLASS_HID_00af] = 13,
	[BNXT_ULP_CLASS_HID_00d3] = 14,
	[BNXT_ULP_CLASS_HID_005b] = 15,
	[BNXT_ULP_CLASS_HID_00ad] = 16,
	[BNXT_ULP_CLASS_HID_0091] = 17,
	[BNXT_ULP_CLASS_HID_00fb] = 18,
	[BNXT_ULP_CLASS_HID_0063] = 19,
	[BNXT_ULP_CLASS_HID_0097] = 20,
	[BNXT_ULP_CLASS_HID_00cc] = 21,
	[BNXT_ULP_CLASS_HID_00f0] = 22,
	[BNXT_ULP_CLASS_HID_00c0] = 23,
	[BNXT_ULP_CLASS_HID_002a] = 24,
	[BNXT_ULP_CLASS_HID_00c7] = 25,
	[BNXT_ULP_CLASS_HID_0029] = 26,
	[BNXT_ULP_CLASS_HID_00d1] = 27,
	[BNXT_ULP_CLASS_HID_003b] = 28,
	[BNXT_ULP_CLASS_HID_00ef] = 29,
	[BNXT_ULP_CLASS_HID_0013] = 30,
	[BNXT_ULP_CLASS_HID_009b] = 31,
	[BNXT_ULP_CLASS_HID_00ed] = 32,
	[BNXT_ULP_CLASS_HID_002d] = 33,
	[BNXT_ULP_CLASS_HID_0051] = 34,
	[BNXT_ULP_CLASS_HID_00d9] = 35,
	[BNXT_ULP_CLASS_HID_0023] = 36,
	[BNXT_ULP_CLASS_HID_0017] = 37,
	[BNXT_ULP_CLASS_HID_0079] = 38,
	[BNXT_ULP_CLASS_HID_00e1] = 39,
	[BNXT_ULP_CLASS_HID_0015] = 40
};

/* Array for the proto matcher list */
struct bnxt_ulp_class_match_info ulp_class_match_list[] = {
	[1] = {
	.class_hid = BNXT_ULP_CLASS_HID_00fc,
	.class_tid = 1,
	.hdr_sig_id = 0,
	.flow_sig_id = 0,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[2] = {
	.class_hid = BNXT_ULP_CLASS_HID_0046,
	.class_tid = 1,
	.hdr_sig_id = 0,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_0_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[3] = {
	.class_hid = BNXT_ULP_CLASS_HID_0056,
	.class_tid = 1,
	.hdr_sig_id = 0,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[4] = {
	.class_hid = BNXT_ULP_CLASS_HID_00b8,
	.class_tid = 1,
	.hdr_sig_id = 0,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_0_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[5] = {
	.class_hid = BNXT_ULP_CLASS_HID_0041,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[6] = {
	.class_hid = BNXT_ULP_CLASS_HID_00ab,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[7] = {
	.class_hid = BNXT_ULP_CLASS_HID_0053,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[8] = {
	.class_hid = BNXT_ULP_CLASS_HID_00a5,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[9] = {
	.class_hid = BNXT_ULP_CLASS_HID_0069,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[10] = {
	.class_hid = BNXT_ULP_CLASS_HID_009d,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[11] = {
	.class_hid = BNXT_ULP_CLASS_HID_0005,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[12] = {
	.class_hid = BNXT_ULP_CLASS_HID_006f,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[13] = {
	.class_hid = BNXT_ULP_CLASS_HID_00af,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[14] = {
	.class_hid = BNXT_ULP_CLASS_HID_00d3,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[15] = {
	.class_hid = BNXT_ULP_CLASS_HID_005b,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[16] = {
	.class_hid = BNXT_ULP_CLASS_HID_00ad,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[17] = {
	.class_hid = BNXT_ULP_CLASS_HID_0091,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[18] = {
	.class_hid = BNXT_ULP_CLASS_HID_00fb,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[19] = {
	.class_hid = BNXT_ULP_CLASS_HID_0063,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[20] = {
	.class_hid = BNXT_ULP_CLASS_HID_0097,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[21] = {
	.class_hid = BNXT_ULP_CLASS_HID_00cc,
	.class_tid = 2,
	.hdr_sig_id = 0,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[22] = {
	.class_hid = BNXT_ULP_CLASS_HID_00f0,
	.class_tid = 2,
	.hdr_sig_id = 0,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_0_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[23] = {
	.class_hid = BNXT_ULP_CLASS_HID_00c0,
	.class_tid = 2,
	.hdr_sig_id = 0,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_0_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[24] = {
	.class_hid = BNXT_ULP_CLASS_HID_002a,
	.class_tid = 2,
	.hdr_sig_id = 0,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_0_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_0_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[25] = {
	.class_hid = BNXT_ULP_CLASS_HID_00c7,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[26] = {
	.class_hid = BNXT_ULP_CLASS_HID_0029,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[27] = {
	.class_hid = BNXT_ULP_CLASS_HID_00d1,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[28] = {
	.class_hid = BNXT_ULP_CLASS_HID_003b,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[29] = {
	.class_hid = BNXT_ULP_CLASS_HID_00ef,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[30] = {
	.class_hid = BNXT_ULP_CLASS_HID_0013,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[31] = {
	.class_hid = BNXT_ULP_CLASS_HID_009b,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[32] = {
	.class_hid = BNXT_ULP_CLASS_HID_00ed,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[33] = {
	.class_hid = BNXT_ULP_CLASS_HID_002d,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[34] = {
	.class_hid = BNXT_ULP_CLASS_HID_0051,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[35] = {
	.class_hid = BNXT_ULP_CLASS_HID_00d9,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[36] = {
	.class_hid = BNXT_ULP_CLASS_HID_0023,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[37] = {
	.class_hid = BNXT_ULP_CLASS_HID_0017,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[38] = {
	.class_hid = BNXT_ULP_CLASS_HID_0079,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[39] = {
	.class_hid = BNXT_ULP_CLASS_HID_00e1,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[40] = {
	.class_hid = BNXT_ULP_CLASS_HID_0015,
	.class_tid = 2,
	.hdr_sig_id = 1,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF2_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF2_1_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF2_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF2_1_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	}
};
