/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2014-2021 Broadcom
 * All rights reserved.
 */

/* date: Mon Dec  7 09:51:03 2020 */

#include "ulp_template_db_enum.h"
#include "ulp_template_db_field.h"
#include "ulp_template_struct.h"
#include "ulp_template_db_tbl.h"

/* Define the template structures */
/*
 * Classification signature table:
 * maps hash id to ulp_class_match_list[] index
 */
uint16_t ulp_class_sig_tbl[BNXT_ULP_CLASS_SIG_TBL_MAX_SZ] = {
	[BNXT_ULP_CLASS_HID_005c] = 1,
	[BNXT_ULP_CLASS_HID_0003] = 2,
	[BNXT_ULP_CLASS_HID_0132] = 3,
	[BNXT_ULP_CLASS_HID_00e1] = 4,
	[BNXT_ULP_CLASS_HID_0044] = 5,
	[BNXT_ULP_CLASS_HID_001b] = 6,
	[BNXT_ULP_CLASS_HID_012a] = 7,
	[BNXT_ULP_CLASS_HID_00f9] = 8,
	[BNXT_ULP_CLASS_HID_018d] = 9,
	[BNXT_ULP_CLASS_HID_00a7] = 10,
	[BNXT_ULP_CLASS_HID_006f] = 11,
	[BNXT_ULP_CLASS_HID_0181] = 12,
	[BNXT_ULP_CLASS_HID_0195] = 13,
	[BNXT_ULP_CLASS_HID_00bf] = 14,
	[BNXT_ULP_CLASS_HID_0077] = 15,
	[BNXT_ULP_CLASS_HID_0199] = 16,
	[BNXT_ULP_CLASS_HID_009a] = 17,
	[BNXT_ULP_CLASS_HID_0192] = 18,
	[BNXT_ULP_CLASS_HID_01e2] = 19,
	[BNXT_ULP_CLASS_HID_00fa] = 20,
	[BNXT_ULP_CLASS_HID_0165] = 21,
	[BNXT_ULP_CLASS_HID_0042] = 22,
	[BNXT_ULP_CLASS_HID_00cd] = 23,
	[BNXT_ULP_CLASS_HID_01aa] = 24,
	[BNXT_ULP_CLASS_HID_0178] = 25,
	[BNXT_ULP_CLASS_HID_0070] = 26,
	[BNXT_ULP_CLASS_HID_00f3] = 27,
	[BNXT_ULP_CLASS_HID_01d8] = 28,
	[BNXT_ULP_CLASS_HID_005b] = 29,
	[BNXT_ULP_CLASS_HID_0153] = 30,
	[BNXT_ULP_CLASS_HID_01a3] = 31,
	[BNXT_ULP_CLASS_HID_00bb] = 32,
	[BNXT_ULP_CLASS_HID_0082] = 33,
	[BNXT_ULP_CLASS_HID_018a] = 34,
	[BNXT_ULP_CLASS_HID_01fa] = 35,
	[BNXT_ULP_CLASS_HID_00e2] = 36,
	[BNXT_ULP_CLASS_HID_017d] = 37,
	[BNXT_ULP_CLASS_HID_005a] = 38,
	[BNXT_ULP_CLASS_HID_00d5] = 39,
	[BNXT_ULP_CLASS_HID_01b2] = 40,
	[BNXT_ULP_CLASS_HID_0160] = 41,
	[BNXT_ULP_CLASS_HID_0068] = 42,
	[BNXT_ULP_CLASS_HID_00eb] = 43,
	[BNXT_ULP_CLASS_HID_01c0] = 44,
	[BNXT_ULP_CLASS_HID_0043] = 45,
	[BNXT_ULP_CLASS_HID_014b] = 46,
	[BNXT_ULP_CLASS_HID_01bb] = 47,
	[BNXT_ULP_CLASS_HID_00a3] = 48,
	[BNXT_ULP_CLASS_HID_00cb] = 49,
	[BNXT_ULP_CLASS_HID_00b4] = 50,
	[BNXT_ULP_CLASS_HID_0013] = 51,
	[BNXT_ULP_CLASS_HID_001c] = 52,
	[BNXT_ULP_CLASS_HID_017b] = 53,
	[BNXT_ULP_CLASS_HID_0164] = 54,
	[BNXT_ULP_CLASS_HID_00c3] = 55,
	[BNXT_ULP_CLASS_HID_00cc] = 56,
	[BNXT_ULP_CLASS_HID_01a5] = 57,
	[BNXT_ULP_CLASS_HID_0196] = 58,
	[BNXT_ULP_CLASS_HID_010d] = 59,
	[BNXT_ULP_CLASS_HID_00fe] = 60,
	[BNXT_ULP_CLASS_HID_0084] = 61,
	[BNXT_ULP_CLASS_HID_0046] = 62,
	[BNXT_ULP_CLASS_HID_01ec] = 63,
	[BNXT_ULP_CLASS_HID_01ae] = 64,
	[BNXT_ULP_CLASS_HID_00d3] = 65,
	[BNXT_ULP_CLASS_HID_00ac] = 66,
	[BNXT_ULP_CLASS_HID_000b] = 67,
	[BNXT_ULP_CLASS_HID_0004] = 68,
	[BNXT_ULP_CLASS_HID_0163] = 69,
	[BNXT_ULP_CLASS_HID_017c] = 70,
	[BNXT_ULP_CLASS_HID_00db] = 71,
	[BNXT_ULP_CLASS_HID_00d4] = 72,
	[BNXT_ULP_CLASS_HID_01bd] = 73,
	[BNXT_ULP_CLASS_HID_018e] = 74,
	[BNXT_ULP_CLASS_HID_0115] = 75,
	[BNXT_ULP_CLASS_HID_00e6] = 76,
	[BNXT_ULP_CLASS_HID_009c] = 77,
	[BNXT_ULP_CLASS_HID_005e] = 78,
	[BNXT_ULP_CLASS_HID_01f4] = 79,
	[BNXT_ULP_CLASS_HID_01b6] = 80
};

/* Array for the proto matcher list */
struct bnxt_ulp_class_match_info ulp_class_match_list[] = {
	[1] = {
	.class_hid = BNXT_ULP_CLASS_HID_005c,
	.class_tid = 1,
	.hdr_sig_id = 0,
	.flow_sig_id = 0,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_0_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[2] = {
	.class_hid = BNXT_ULP_CLASS_HID_0003,
	.class_tid = 1,
	.hdr_sig_id = 0,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_0_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[3] = {
	.class_hid = BNXT_ULP_CLASS_HID_0132,
	.class_tid = 1,
	.hdr_sig_id = 0,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[4] = {
	.class_hid = BNXT_ULP_CLASS_HID_00e1,
	.class_tid = 1,
	.hdr_sig_id = 0,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_0_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_0_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[5] = {
	.class_hid = BNXT_ULP_CLASS_HID_0044,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 1,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[6] = {
	.class_hid = BNXT_ULP_CLASS_HID_001b,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[7] = {
	.class_hid = BNXT_ULP_CLASS_HID_012a,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[8] = {
	.class_hid = BNXT_ULP_CLASS_HID_00f9,
	.class_tid = 1,
	.hdr_sig_id = 1,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_1_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_1_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_1_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[9] = {
	.class_hid = BNXT_ULP_CLASS_HID_018d,
	.class_tid = 1,
	.hdr_sig_id = 2,
	.flow_sig_id = 2,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_2_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_2_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_2_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_2_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[10] = {
	.class_hid = BNXT_ULP_CLASS_HID_00a7,
	.class_tid = 1,
	.hdr_sig_id = 2,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_2_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_2_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_2_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_2_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[11] = {
	.class_hid = BNXT_ULP_CLASS_HID_006f,
	.class_tid = 1,
	.hdr_sig_id = 2,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_2_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_2_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_2_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[12] = {
	.class_hid = BNXT_ULP_CLASS_HID_0181,
	.class_tid = 1,
	.hdr_sig_id = 2,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_2_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_2_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_2_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_2_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[13] = {
	.class_hid = BNXT_ULP_CLASS_HID_0195,
	.class_tid = 1,
	.hdr_sig_id = 3,
	.flow_sig_id = 3,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_3_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_3_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_3_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_3_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[14] = {
	.class_hid = BNXT_ULP_CLASS_HID_00bf,
	.class_tid = 1,
	.hdr_sig_id = 3,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_3_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_3_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_3_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_3_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[15] = {
	.class_hid = BNXT_ULP_CLASS_HID_0077,
	.class_tid = 1,
	.hdr_sig_id = 3,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_3_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_3_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_3_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[16] = {
	.class_hid = BNXT_ULP_CLASS_HID_0199,
	.class_tid = 1,
	.hdr_sig_id = 3,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_3_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_3_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_3_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_3_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[17] = {
	.class_hid = BNXT_ULP_CLASS_HID_009a,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[18] = {
	.class_hid = BNXT_ULP_CLASS_HID_0192,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[19] = {
	.class_hid = BNXT_ULP_CLASS_HID_01e2,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[20] = {
	.class_hid = BNXT_ULP_CLASS_HID_00fa,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[21] = {
	.class_hid = BNXT_ULP_CLASS_HID_0165,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 4,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[22] = {
	.class_hid = BNXT_ULP_CLASS_HID_0042,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[23] = {
	.class_hid = BNXT_ULP_CLASS_HID_00cd,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[24] = {
	.class_hid = BNXT_ULP_CLASS_HID_01aa,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[25] = {
	.class_hid = BNXT_ULP_CLASS_HID_0178,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[26] = {
	.class_hid = BNXT_ULP_CLASS_HID_0070,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[27] = {
	.class_hid = BNXT_ULP_CLASS_HID_00f3,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[28] = {
	.class_hid = BNXT_ULP_CLASS_HID_01d8,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[29] = {
	.class_hid = BNXT_ULP_CLASS_HID_005b,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[30] = {
	.class_hid = BNXT_ULP_CLASS_HID_0153,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[31] = {
	.class_hid = BNXT_ULP_CLASS_HID_01a3,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[32] = {
	.class_hid = BNXT_ULP_CLASS_HID_00bb,
	.class_tid = 1,
	.hdr_sig_id = 4,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_4_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_4_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_4_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[33] = {
	.class_hid = BNXT_ULP_CLASS_HID_0082,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[34] = {
	.class_hid = BNXT_ULP_CLASS_HID_018a,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[35] = {
	.class_hid = BNXT_ULP_CLASS_HID_01fa,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[36] = {
	.class_hid = BNXT_ULP_CLASS_HID_00e2,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[37] = {
	.class_hid = BNXT_ULP_CLASS_HID_017d,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 5,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[38] = {
	.class_hid = BNXT_ULP_CLASS_HID_005a,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[39] = {
	.class_hid = BNXT_ULP_CLASS_HID_00d5,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[40] = {
	.class_hid = BNXT_ULP_CLASS_HID_01b2,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[41] = {
	.class_hid = BNXT_ULP_CLASS_HID_0160,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[42] = {
	.class_hid = BNXT_ULP_CLASS_HID_0068,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[43] = {
	.class_hid = BNXT_ULP_CLASS_HID_00eb,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[44] = {
	.class_hid = BNXT_ULP_CLASS_HID_01c0,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[45] = {
	.class_hid = BNXT_ULP_CLASS_HID_0043,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[46] = {
	.class_hid = BNXT_ULP_CLASS_HID_014b,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[47] = {
	.class_hid = BNXT_ULP_CLASS_HID_01bb,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_PROTO_ID |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[48] = {
	.class_hid = BNXT_ULP_CLASS_HID_00a3,
	.class_tid = 1,
	.hdr_sig_id = 5,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV4 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_5_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_5_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_SRC_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_IPV4_DST_ADDR |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_5_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[49] = {
	.class_hid = BNXT_ULP_CLASS_HID_00cb,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[50] = {
	.class_hid = BNXT_ULP_CLASS_HID_00b4,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[51] = {
	.class_hid = BNXT_ULP_CLASS_HID_0013,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[52] = {
	.class_hid = BNXT_ULP_CLASS_HID_001c,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[53] = {
	.class_hid = BNXT_ULP_CLASS_HID_017b,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 6,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[54] = {
	.class_hid = BNXT_ULP_CLASS_HID_0164,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[55] = {
	.class_hid = BNXT_ULP_CLASS_HID_00c3,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[56] = {
	.class_hid = BNXT_ULP_CLASS_HID_00cc,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[57] = {
	.class_hid = BNXT_ULP_CLASS_HID_01a5,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[58] = {
	.class_hid = BNXT_ULP_CLASS_HID_0196,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[59] = {
	.class_hid = BNXT_ULP_CLASS_HID_010d,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[60] = {
	.class_hid = BNXT_ULP_CLASS_HID_00fe,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[61] = {
	.class_hid = BNXT_ULP_CLASS_HID_0084,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[62] = {
	.class_hid = BNXT_ULP_CLASS_HID_0046,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[63] = {
	.class_hid = BNXT_ULP_CLASS_HID_01ec,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[64] = {
	.class_hid = BNXT_ULP_CLASS_HID_01ae,
	.class_tid = 1,
	.hdr_sig_id = 6,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_TCP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_6_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_6_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_SRC_PORT |
		BNXT_ULP_HF1_6_BITMASK_O_TCP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[65] = {
	.class_hid = BNXT_ULP_CLASS_HID_00d3,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[66] = {
	.class_hid = BNXT_ULP_CLASS_HID_00ac,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[67] = {
	.class_hid = BNXT_ULP_CLASS_HID_000b,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[68] = {
	.class_hid = BNXT_ULP_CLASS_HID_0004,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[69] = {
	.class_hid = BNXT_ULP_CLASS_HID_0163,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 7,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[70] = {
	.class_hid = BNXT_ULP_CLASS_HID_017c,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[71] = {
	.class_hid = BNXT_ULP_CLASS_HID_00db,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[72] = {
	.class_hid = BNXT_ULP_CLASS_HID_00d4,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_ETH_TYPE |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[73] = {
	.class_hid = BNXT_ULP_CLASS_HID_01bd,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[74] = {
	.class_hid = BNXT_ULP_CLASS_HID_018e,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[75] = {
	.class_hid = BNXT_ULP_CLASS_HID_0115,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[76] = {
	.class_hid = BNXT_ULP_CLASS_HID_00e6,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[77] = {
	.class_hid = BNXT_ULP_CLASS_HID_009c,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[78] = {
	.class_hid = BNXT_ULP_CLASS_HID_005e,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[79] = {
	.class_hid = BNXT_ULP_CLASS_HID_01f4,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_PROTO_ID |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	},
	[80] = {
	.class_hid = BNXT_ULP_CLASS_HID_01b6,
	.class_tid = 1,
	.hdr_sig_id = 7,
	.flow_sig_id = 8,
	.hdr_sig = { .bits =
		BNXT_ULP_HDR_BIT_O_ETH |
		BNXT_ULP_HDR_BIT_OO_VLAN |
		BNXT_ULP_HDR_BIT_O_IPV6 |
		BNXT_ULP_HDR_BIT_O_UDP |
		BNXT_ULP_FLOW_DIR_BITMASK_ING },
	.field_sig = { .bits =
		BNXT_ULP_HF1_7_BITMASK_O_ETH_DMAC |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_VID |
		BNXT_ULP_HF1_7_BITMASK_OO_VLAN_TYPE |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_SRC_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_IPV6_DST_ADDR |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_SRC_PORT |
		BNXT_ULP_HF1_7_BITMASK_O_UDP_DST_PORT |
		BNXT_ULP_MATCH_TYPE_BITMASK_EM },
	}
};
