/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright (C), 2025, Wuxi Stars Micro System Technologies Co., Ltd.
 */

#ifndef SXE2_TXRX_COMMON_H
#define SXE2_TXRX_COMMON_H

#include <stdbool.h>

#define SXE2_ALIGN_RING_DESC      32
#define SXE2_MIN_RING_DESC        64
#define SXE2_MAX_RING_DESC        4096

#define SXE2_VECTOR_PATH               0
#define SXE2_VECTOR_OFFLOAD_PATH       1
#define SXE2_VECTOR_CTX_OFFLOAD_PATH   2

#define SXE2_MAX_PTYPE_NUM     1024
#define SXE2_MIN_BUF_SIZE      1024

#define SXE2_ALIGN                32
#define SXE2_DESC_ADDR_ALIGN      128

#define SXE2_MIN_TSO_MSS       88
#define SXE2_MAX_TSO_MSS       9728

#define SXE2_TX_MTU_SEG_MAX      15

#define SXE2_TX_MIN_PKT_LEN    17
#define SXE2_TX_MAX_BURST      32
#define SXE2_TX_MAX_FREE_BUF   64
#define SXE2_TX_TSO_PKTLEN_MAX        (256ULL * 1024)

#define DEFAULT_TX_RS_THRESH   32
#define DEFAULT_TX_FREE_THRESH 32

#define SXE2_TX_FLAGS_VLAN_TAG_LOC_L2TAG1	RTE_BIT32(0)
#define SXE2_TX_FLAGS_VLAN_TAG_LOC_L2TAG2	RTE_BIT32(1)

#define SXE2_TX_PKTS_BURST_BATCH_NUM	32

union sxe2_tx_offload_info {
	uint64_t data;
	struct {
		uint64_t l2_len:7;
		uint64_t l3_len:9;
		uint64_t l4_len:8;
		uint64_t tso_segsz:16;
		uint64_t outer_l2_len:8;
		uint64_t outer_l3_len:16;
	};
};

#define SXE2_TX_OFFLOAD_CTXT_NEEDCK_MASK (RTE_MBUF_F_TX_TCP_SEG | \
				RTE_MBUF_F_TX_UDP_SEG | \
				RTE_MBUF_F_TX_QINQ | \
				RTE_MBUF_F_TX_OUTER_IP_CKSUM | \
				RTE_MBUF_F_TX_OUTER_UDP_CKSUM | \
				RTE_MBUF_F_TX_SEC_OFFLOAD | \
				RTE_MBUF_F_TX_IEEE1588_TMST)

#define SXE2_TX_OFFLOAD_CKSUM_MASK (RTE_MBUF_F_TX_IP_CKSUM | \
				RTE_MBUF_F_TX_L4_MASK | \
				RTE_MBUF_F_TX_TCP_SEG | \
				RTE_MBUF_F_TX_UDP_SEG | \
				RTE_MBUF_F_TX_OUTER_UDP_CKSUM | \
				RTE_MBUF_F_TX_OUTER_IP_CKSUM)

struct sxe2_tx_context_desc {
	uint32_t tunneling_params;
	uint16_t l2tag2;
	uint16_t ipsec_offset;
	uint64_t type_cmd_tso_mss;
};

#define SXE2_TX_CTXT_DESC_EIPLEN_SHIFT	2
#define SXE2_TX_CTXT_DESC_L4TUNT_SHIFT	9
#define SXE2_TX_CTXT_DESC_NATLEN_SHIFT	12
#define SXE2_TX_CTXT_DESC_L4T_CS_SHIFT	23

#define SXE2_TX_CTXT_DESC_CMD_SHIFT			4
#define SXE2_TX_CTXT_DESC_IPSEC_MODE_SHIFT	11
#define SXE2_TX_CTXT_DESC_IPSEC_EN_SHIFT		12
#define SXE2_TX_CTXT_DESC_IPSEC_ENGINE_SHIFT	13
#define SXE2_TX_CTXT_DESC_IPSEC_SA_SHIFT		16
#define SXE2_TX_CTXT_DESC_TSO_LEN_SHIFT		30
#define SXE2_TX_CTXT_DESC_MSS_SHIFT			50
#define SXE2_TX_CTXT_DESC_VSI_SHIFT	        50

#define SXE2_TX_CTXT_DESC_L4T_CS_MASK  RTE_BIT64(SXE2_TX_CTXT_DESC_L4T_CS_SHIFT)

#define SXE2_TX_CTXT_DESC_EIPLEN_VAL(val) \
		(((val) >> 2) << SXE2_TX_CTXT_DESC_EIPLEN_SHIFT)
#define SXE2_TX_CTXT_DESC_NATLEN_VAL(val) \
		(((val) >> 1) << SXE2_TX_CTXT_DESC_NATLEN_SHIFT)

enum sxe2_tx_ctxt_desc_eipt_bits {
	SXE2_TX_CTXT_DESC_EIPT_NONE         = 0x0,
	SXE2_TX_CTXT_DESC_EIPT_IPV6         = 0x1,
	SXE2_TX_CTXT_DESC_EIPT_IPV4_NO_CSUM = 0x2,
	SXE2_TX_CTXT_DESC_EIPT_IPV4         = 0x3,
};

enum sxe2_tx_ctxt_desc_l4tunt_bits {
	SXE2_TX_CTXT_DESC_UDP_TUNNE = 0x1 << SXE2_TX_CTXT_DESC_L4TUNT_SHIFT,
	SXE2_TX_CTXT_DESC_GRE_TUNNE = 0x2 << SXE2_TX_CTXT_DESC_L4TUNT_SHIFT,
};

enum sxe2_tx_ctxt_desc_cmd_bits {
	SXE2_TX_CTXT_DESC_CMD_TSO          = 0x01,
	SXE2_TX_CTXT_DESC_CMD_TSYN         = 0x02,
	SXE2_TX_CTXT_DESC_CMD_IL2TAG2      = 0x04,
	SXE2_TX_CTXT_DESC_CMD_IL2TAG2_IL2H = 0x08,
	SXE2_TX_CTXT_DESC_CMD_SWTCH_NOTAG  = 0x00,
	SXE2_TX_CTXT_DESC_CMD_SWTCH_UPLINK = 0x10,
	SXE2_TX_CTXT_DESC_CMD_SWTCH_LOCAL  = 0x20,
	SXE2_TX_CTXT_DESC_CMD_SWTCH_VSI    = 0x30,
	SXE2_TX_CTXT_DESC_CMD_RESERVED     = 0x40
};
#define SXE2_TX_CTXT_DESC_IPSEC_MODE		RTE_BIT64(SXE2_TX_CTXT_DESC_IPSEC_MODE_SHIFT)
#define SXE2_TX_CTXT_DESC_IPSEC_EN		RTE_BIT64(SXE2_TX_CTXT_DESC_IPSEC_EN_SHIFT)
#define SXE2_TX_CTXT_DESC_IPSEC_ENGINE	RTE_BIT64(SXE2_TX_CTXT_DESC_IPSEC_ENGINE_SHIFT)
#define SXE2_TX_CTXT_DESC_CMD_TSYN_MASK   \
		(((uint64_t)SXE2_TX_CTXT_DESC_CMD_TSYN) << SXE2_TX_CTXT_DESC_CMD_SHIFT)
#define SXE2_TX_CTXT_DESC_CMD_IL2TAG2_MASK   \
		(((uint64_t)SXE2_TX_CTXT_DESC_CMD_IL2TAG2) << SXE2_TX_CTXT_DESC_CMD_SHIFT)

union sxe2_tx_data_desc {
	struct {
		uint64_t buf_addr;
		uint64_t type_cmd_off_bsz_l2t;
	} read;
	struct {
		uint64_t rsvd;
		uint64_t dd;
	} wb;
};

#define SXE2_TX_DATA_DESC_CMD_SHIFT	4
#define SXE2_TX_DATA_DESC_OFFSET_SHIFT	16
#define SXE2_TX_DATA_DESC_BUF_SZ_SHIFT	34
#define SXE2_TX_DATA_DESC_L2TAG1_SHIFT	48

#define SXE2_TX_DATA_DESC_CMD_MASK	\
		(0xFFFULL   << SXE2_TX_DATA_DESC_CMD_SHIFT)
#define SXE2_TX_DATA_DESC_OFFSET_MASK	\
		(0x3FFFFULL << SXE2_TX_DATA_DESC_OFFSET_SHIFT)
#define SXE2_TX_DATA_DESC_BUF_SZ_MASK	\
		(0x3FFFULL  << SXE2_TX_DATA_DESC_BUF_SZ_SHIFT)
#define SXE2_TX_DATA_DESC_L2TAG1_MASK	\
		(0xFFFFULL  << SXE2_TX_DATA_DESC_L2TAG1_SHIFT)

#define SXE2_TX_DESC_LENGTH_MACLEN_SHIFT		 (0)
#define SXE2_TX_DESC_LENGTH_IPLEN_SHIFT		 (7)
#define SXE2_TX_DESC_LENGTH_L4_FC_LEN_SHIFT	 (14)

#define SXE2_TX_DESC_DTYPE_MASK	0xF
#define SXE2_TX_DATA_DESC_MACLEN_MASK \
		(0x7FULL << SXE2_TX_DESC_LENGTH_MACLEN_SHIFT)
#define SXE2_TX_DATA_DESC_IPLEN_MASK  \
		(0x7FULL << SXE2_TX_DESC_LENGTH_IPLEN_SHIFT)
#define SXE2_TX_DATA_DESC_L4LEN_MASK  \
		(0xFULL  << SXE2_TX_DESC_LENGTH_L4_FC_LEN_SHIFT)

#define SXE2_TX_DATA_DESC_MACLEN_VAL(val)	\
	(((val) >> 1) << SXE2_TX_DESC_LENGTH_MACLEN_SHIFT)
#define SXE2_TX_DATA_DESC_IPLEN_VAL(val)	\
	(((val) >> 2) << SXE2_TX_DESC_LENGTH_IPLEN_SHIFT)
#define SXE2_TX_DATA_DESC_L4LEN_VAL(val)	\
	(((val) >> 2) << SXE2_TX_DESC_LENGTH_L4_FC_LEN_SHIFT)

enum sxe2_tx_desc_type {
	SXE2_TX_DESC_DTYPE_DATA      = 0x0,
	SXE2_TX_DESC_DTYPE_CTXT      = 0x1,
	SXE2_TX_DESC_DTYPE_FLTR_PROG = 0x8,
	SXE2_TX_DESC_DTYPE_DESC_DONE = 0xF,
};

enum sxe2_tx_data_desc_cmd_bits {
	SXE2_TX_DATA_DESC_CMD_EOP            = 0x0001,
	SXE2_TX_DATA_DESC_CMD_RS             = 0x0002,
	SXE2_TX_DATA_DESC_CMD_MACSEC         = 0x0004,
	SXE2_TX_DATA_DESC_CMD_IL2TAG1        = 0x0008,
	SXE2_TX_DATA_DESC_CMD_DUMMY          = 0x0010,
	SXE2_TX_DATA_DESC_CMD_IIPT_IPV6      = 0x0020,
	SXE2_TX_DATA_DESC_CMD_IIPT_IPV4      = 0x0040,
	SXE2_TX_DATA_DESC_CMD_IIPT_IPV4_CSUM = 0x0060,
	SXE2_TX_DATA_DESC_CMD_L4T_EOFT_TCP   = 0x0100,
	SXE2_TX_DATA_DESC_CMD_L4T_EOFT_SCTP  = 0x0200,
	SXE2_TX_DATA_DESC_CMD_L4T_EOFT_UDP   = 0x0300,
	SXE2_TX_DATA_DESC_CMD_RE             = 0x0400
};
#define SXE2_TX_DATA_DESC_CMD_RS_MASK	\
		(((uint64_t)SXE2_TX_DATA_DESC_CMD_RS) << SXE2_TX_DATA_DESC_CMD_SHIFT)

#define SXE2_TX_MAX_DATA_NUM_PER_DESC	0X3FFFUL

#define SXE2_TX_DESC_RING_ALIGN	\
	(SXE2_ALIGN_RING_DESC / sizeof(union sxe2_tx_data_desc))

#define SXE2_TX_DESC_DTYPE_DESC_MASK 0xF

#define SXE2_TX_FILL_PER_LOOP          4
#define SXE2_TX_FILL_PER_LOOP_MASK     (SXE2_TX_FILL_PER_LOOP - 1)
#define SXE2_TX_FREE_BUFFER_SIZE_MAX  (64)

#define SXE2_RX_MAX_BURST              32
#define SXE2_RING_SIZE_MIN             1024
#define SXE2_RX_MAX_NSEG               2

#define SXE2_RX_PKTS_BURST_BATCH_NUM	  SXE2_RX_MAX_BURST
#define SXE2_VPMD_RX_MAX_BURST         SXE2_RX_MAX_BURST

#define SXE2_RXQ_CTX_DBUFF_SHIFT       7

#define SXE2_RX_NUM_PER_LOOP			8

#define SXE2_RX_FLEX_DESC_PTYPE_S      (16)
#define SXE2_RX_FLEX_DESC_PTYPE_M      (0x3FFULL)

#define SXE2_RX_HBUF_LEN_UNIT          6
#define SXE2_RX_LDW_LEN_UNIT           6
#define SXE2_RX_DBUF_LEN_UNIT          7
#define SXE2_RX_DBUF_LEN_MASK          (~0x7F)

#define SXE2_RX_PKTS_TS_TIMEOUT_VAL	200

#define SXE2_RX_VECTOR_OFFLOAD (			 \
		RTE_ETH_RX_OFFLOAD_CHECKSUM   |		 \
		RTE_ETH_RX_OFFLOAD_SCTP_CKSUM |		 \
		RTE_ETH_RX_OFFLOAD_VLAN       |		 \
		RTE_ETH_RX_OFFLOAD_RSS_HASH   |		 \
		RTE_ETH_RX_OFFLOAD_TIMESTAMP)

#define SXE2_DEFAULT_RX_FREE_THRESH  32
#define SXE2_DEFAULT_RX_PTHRESH      8
#define SXE2_DEFAULT_RX_HTHRESH      8
#define SXE2_DEFAULT_RX_WTHRESH      0

#define SXE2_DEFAULT_TX_FREE_THRESH  32
#define SXE2_DEFAULT_TX_PTHRESH      32
#define SXE2_DEFAULT_TX_HTHRESH      0
#define SXE2_DEFAULT_TX_WTHRESH      0
#define SXE2_DEFAULT_TX_RSBIT_THRESH 32

#define SXE2_RX_SEG_NUM          2

#ifdef RTE_LIBRTE_SXE2_16BYTE_RX_DESC
#define sxe2_rx_desc sxe2_rx_16b_desc
#else
#define sxe2_rx_desc sxe2_rx_32b_desc
#endif

union sxe2_rx_16b_desc {
	struct {
		uint64_t pkt_addr;
		uint64_t hdr_addr;
	} read;
	struct {
		uint8_t rxdid_src;
		uint8_t mirror;
		uint16_t l2tag1;
		uint32_t filter_status;

		uint64_t status_err_ptype_len;
	} wb;
};

union sxe2_rx_32b_desc {
	struct {
		uint64_t pkt_addr;
		uint64_t hdr_addr;
		uint64_t rsvd1;
		uint64_t rsvd2;
	} read;
	struct {
		uint8_t rxdid_src;
		uint8_t mirror;
		uint16_t l2tag1;
		uint32_t filter_status;

		uint64_t status_err_ptype_len;

		uint32_t status_lrocnt_fdpf_id;
		uint16_t l2tag2_1st;
		uint16_t l2tag2_2nd;

		uint8_t acl_pf_id;
		uint8_t sw_pf_id;
		uint16_t flow_id;

		uint32_t fd_filter_id;

	} wb;
	struct {
		uint8_t rxdid_src_fd_eudpe;
		uint8_t mirror;
		uint16_t l2_tag1;
		uint32_t filter_status;

		uint64_t status_err_ptype_len;

		uint32_t ext_status_ts_low;
		uint16_t l2tag2_1st;
		uint16_t l2tag2_2nd;

		uint32_t ts_h;
		uint32_t fd_filter_id;

	} wb_ts;
};

enum sxe2_rx_lro_desc_max_num {
	SXE2_RX_LRO_DESC_MAX_1   = 1,
	SXE2_RX_LRO_DESC_MAX_4   = 4,
	SXE2_RX_LRO_DESC_MAX_8   = 8,
	SXE2_RX_LRO_DESC_MAX_16  = 16,
	SXE2_RX_LRO_DESC_MAX_32  = 32,
	SXE2_RX_LRO_DESC_MAX_48  = 48,
	SXE2_RX_LRO_DESC_MAX_64  = 64,
	SXE2_RX_LRO_DESC_MAX_NUM = SXE2_RX_LRO_DESC_MAX_64,
};

enum sxe2_rx_desc_rxdid {
	SXE2_RX_DESC_RXDID_16B   = 0,
	SXE2_RX_DESC_RXDID_32B,
	SXE2_RX_DESC_RXDID_1588,
	SXE2_RX_DESC_RXDID_FD,
};

#define SXE2_RX_DESC_RXDID_SHIFT     (0)
#define SXE2_RX_DESC_RXDID_MASK      (0x7 << SXE2_RX_DESC_RXDID_SHIFT)
#define SXE2_RX_DESC_RXDID_VAL_GET(rxdid_src) \
		(((rxdid_src) & SXE2_RX_DESC_RXDID_MASK) >> SXE2_RX_DESC_RXDID_SHIFT)

#define SXE2_RX_DESC_PKT_SRC_SHIFT     (3)
#define SXE2_RX_DESC_PKT_SRC_MASK      (0x3 << SXE2_RX_DESC_PKT_SRC_SHIFT)
#define SXE2_RX_DESC_PKT_SRC_VAL_GET(rxdid_src) \
		(((rxdid_src) & SXE2_RX_DESC_PKT_SRC_MASK) >> SXE2_RX_DESC_PKT_SRC_SHIFT)

#define SXE2_RX_DESC_FD_VLD_SHIFT     (5)
#define SXE2_RX_DESC_FD_VLD_MASK      (0x1 << SXE2_RX_DESC_FD_VLD_SHIFT)
#define SXE2_RX_DESC_FD_VLD_VAL_GET(rxdid_src) \
		(((rxdid_src) & SXE2_RX_DESC_FD_VLD_MASK) >> SXE2_RX_DESC_FD_VLD_SHIFT)

#define SXE2_RX_DESC_EUDPE_SHIFT     (6)
#define SXE2_RX_DESC_EUDPE_MASK      (0x1 << SXE2_RX_DESC_EUDPE_SHIFT)
#define SXE2_RX_DESC_EUDPE_VAL_GET(rxdid_src) \
		(((rxdid_src) & SXE2_RX_DESC_EUDPE_MASK) >> SXE2_RX_DESC_EUDPE_SHIFT)

#define SXE2_RX_DESC_UDP_NET_SHIFT     (7)
#define SXE2_RX_DESC_UDP_NET_MASK      (0x1 << SXE2_RX_DESC_UDP_NET_SHIFT)
#define SXE2_RX_DESC_UDP_NET_VAL_GET(rxdid_src) \
		(((rxdid_src) & SXE2_RX_DESC_UDP_NET_MASK) >> SXE2_RX_DESC_UDP_NET_SHIFT)

#define SXE2_RX_DESC_MIRR_ID_SHIFT   (0)
#define SXE2_RX_DESC_MIRR_ID_MASK    (0x3F << SXE2_RX_DESC_MIRR_ID_SHIFT)
#define SXE2_RX_DESC_MIRR_ID_VAL_GET(mirr) \
		(((mirr) & SXE2_RX_DESC_MIRR_ID_MASK) >> SXE2_RX_DESC_MIRR_ID_SHIFT)

#define SXE2_RX_DESC_MIRR_TYPE_SHIFT   (6)
#define SXE2_RX_DESC_MIRR_TYPE_MASK    (0x3 << SXE2_RX_DESC_MIRR_TYPE_SHIFT)
#define SXE2_RX_DESC_MIRR_TYPE_VAL_GET(mirr) \
		(((mirr) & SXE2_RX_DESC_MIRR_TYPE_MASK) >> SXE2_RX_DESC_MIRR_TYPE_SHIFT)

#define SXE2_RX_DESC_PKT_LEN_SHIFT   (32)
#define SXE2_RX_DESC_PKT_LEN_MASK    (0x3FFFULL << SXE2_RX_DESC_PKT_LEN_SHIFT)
#define SXE2_RX_DESC_PKT_LEN_VAL_GET(qw1) \
		(((qw1) & SXE2_RX_DESC_PKT_LEN_MASK) >> SXE2_RX_DESC_PKT_LEN_SHIFT)

#define SXE2_RX_DESC_HDR_LEN_SHIFT   (46)
#define SXE2_RX_DESC_HDR_LEN_MASK    (0x7FFULL << SXE2_RX_DESC_HDR_LEN_SHIFT)
#define SXE2_RX_DESC_HDR_LEN_VAL_GET(qw1) \
		(((qw1) & SXE2_RX_DESC_HDR_LEN_MASK) >> SXE2_RX_DESC_HDR_LEN_SHIFT)

#define SXE2_RX_DESC_SPH_SHIFT    (57)
#define SXE2_RX_DESC_SPH_MASK     (0x1ULL << SXE2_RX_DESC_SPH_SHIFT)
#define SXE2_RX_DESC_SPH_VAL_GET(qw1) \
		(((qw1) & SXE2_RX_DESC_SPH_MASK) >> SXE2_RX_DESC_SPH_SHIFT)

#define SXE2_RX_DESC_PTYPE_SHIFT    (16)
#define SXE2_RX_DESC_PTYPE_MASK     (0x3FFULL << SXE2_RX_DESC_PTYPE_SHIFT)
#define SXE2_RX_DESC_PTYPE_MASK_NO_SHIFT (0x3FFULL)
#define SXE2_RX_DESC_PTYPE_VAL_GET(qw1) \
		(((qw1) & SXE2_RX_DESC_PTYPE_MASK) >> SXE2_RX_DESC_PTYPE_SHIFT)

#define SXE2_RX_DESC_FILTER_STATUS_SHIFT   (32)
#define SXE2_RX_DESC_FILTER_STATUS_MASK    (0xFFFFUL)

#define SXE2_RX_DESC_LROCNT_SHIFT   (0)
#define SXE2_RX_DESC_LROCNT_MASK    (0xF)

enum sxe2_rx_desc_status_shift {
	SXE2_RX_DESC_STATUS_DD_SHIFT        = 0,
	SXE2_RX_DESC_STATUS_EOP_SHIFT       = 1,
	SXE2_RX_DESC_STATUS_L2TAG1_P_SHIFT  = 2,

	SXE2_RX_DESC_STATUS_L3L4_P_SHIFT    = 3,
	SXE2_RX_DESC_STATUS_CRCP_SHIFT      = 4,
	SXE2_RX_DESC_STATUS_SECP_SHIFT      = 5,
	SXE2_RX_DESC_STATUS_SECTAG_SHIFT    = 6,
	SXE2_RX_DESC_STATUS_SECE_SHIFT      = 26,
	SXE2_RX_DESC_STATUS_EXT_UDP_0_SHIFT = 27,
	SXE2_RX_DESC_STATUS_UMBCAST_SHIFT   = 28,
	SXE2_RX_DESC_STATUS_PHY_PORT_SHIFT  = 30,
	SXE2_RX_DESC_STATUS_LPBK_SHIFT      = 59,
	SXE2_RX_DESC_STATUS_IPV6_EXADD_SHIFT = 60,
	SXE2_RX_DESC_STATUS_RSS_VLD_SHIFT   = 61,
	SXE2_RX_DESC_STATUS_ACL_HIT_SHIFT   = 62,
	SXE2_RX_DESC_STATUS_INT_UDP_0_SHIFT = 63,
};

#define SXE2_RX_DESC_STATUS_DD_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_DD_SHIFT)
#define SXE2_RX_DESC_STATUS_EOP_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_EOP_SHIFT)
#define SXE2_RX_DESC_STATUS_L2TAG1_P_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_L2TAG1_P_SHIFT)
#define SXE2_RX_DESC_STATUS_L3L4_P_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_L3L4_P_SHIFT)
#define SXE2_RX_DESC_STATUS_CRCP_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_CRCP_SHIFT)
#define SXE2_RX_DESC_STATUS_SECP_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_SECP_SHIFT)
#define SXE2_RX_DESC_STATUS_SECTAG_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_SECTAG_SHIFT)
#define SXE2_RX_DESC_STATUS_SECE_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_SECE_SHIFT)
#define SXE2_RX_DESC_STATUS_EXT_UDP_0_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_EXT_UDP_0_SHIFT)
#define SXE2_RX_DESC_STATUS_UMBCAST_MASK \
		(0x3ULL << SXE2_RX_DESC_STATUS_UMBCAST_SHIFT)
#define SXE2_RX_DESC_STATUS_PHY_PORT_MASK \
		(0x3ULL << SXE2_RX_DESC_STATUS_PHY_PORT_SHIFT)
#define SXE2_RX_DESC_STATUS_LPBK_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_LPBK_SHIFT)
#define SXE2_RX_DESC_STATUS_IPV6_EXADD_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_IPV6_EXADD_SHIFT)
#define SXE2_RX_DESC_STATUS_RSS_VLD_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_RSS_VLD_SHIFT)
#define SXE2_RX_DESC_STATUS_ACL_HIT_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_ACL_HIT_SHIFT)
#define SXE2_RX_DESC_STATUS_INT_UDP_0_MASK \
		(0x1ULL << SXE2_RX_DESC_STATUS_INT_UDP_0_SHIFT)

enum sxe2_rx_desc_umbcast_val {
	SXE2_RX_DESC_STATUS_UNICAST = 0,
	SXE2_RX_DESC_STATUS_MULTICAST = 1,
	SXE2_RX_DESC_STATUS_BROADCAST = 2,
};

#define SXE2_RX_DESC_STATUS_UMBCAST_VAL_GET(qw1) \
		(((qw1) & SXE2_RX_DESC_STATUS_UMBCAST_MASK) >> SXE2_RX_DESC_STATUS_UMBCAST_SHIFT)

enum sxe2_rx_desc_error_shift {
	SXE2_RX_DESC_ERROR_RXE_SHIFT        = 7,
	SXE2_RX_DESC_ERROR_PKT_ECC_SHIFT    = 8,
	SXE2_RX_DESC_ERROR_PKT_HBO_SHIFT    = 9,

	SXE2_RX_DESC_ERROR_CSUM_IPE_SHIFT   = 10,

	SXE2_RX_DESC_ERROR_CSUM_L4_SHIFT    = 11,

	SXE2_RX_DESC_ERROR_CSUM_EIP_SHIFT   = 12,
	SXE2_RX_DESC_ERROR_OVERSIZE_SHIFT   = 13,
	SXE2_RX_DESC_ERROR_SEC_ERR_SHIFT    = 14,
};

#define SXE2_RX_DESC_ERROR_RXE_MASK \
		(0x1ULL << SXE2_RX_DESC_ERROR_RXE_SHIFT)
#define SXE2_RX_DESC_ERROR_PKT_ECC_MASK \
		(0x1ULL << SXE2_RX_DESC_ERROR_PKT_ECC_SHIFT)
#define SXE2_RX_DESC_ERROR_PKT_HBO_MASK \
		(0x1ULL << SXE2_RX_DESC_ERROR_PKT_HBO_SHIFT)
#define SXE2_RX_DESC_ERROR_CSUM_IPE_MASK \
		(0x1ULL << SXE2_RX_DESC_ERROR_CSUM_IPE_SHIFT)
#define SXE2_RX_DESC_ERROR_CSUM_L4_MASK \
		(0x1ULL << SXE2_RX_DESC_ERROR_CSUM_L4_SHIFT)
#define SXE2_RX_DESC_ERROR_CSUM_EIP_MASK \
		(0x1ULL << SXE2_RX_DESC_ERROR_CSUM_EIP_SHIFT)
#define SXE2_RX_DESC_ERROR_OVERSIZE_MASK \
		(0x1ULL << SXE2_RX_DESC_ERROR_OVERSIZE_SHIFT)

#define SXE2_RX_DESC_QW1_ERRORS_MASK \
		(SXE2_RX_DESC_ERROR_CSUM_IPE_MASK | \
			SXE2_RX_DESC_ERROR_CSUM_L4_MASK | \
			SXE2_RX_DESC_ERROR_CSUM_EIP_MASK)

enum sxe2_rx_desc_ext_status_shift {
	SXE2_RX_DESC_EXT_STATUS_L2TAG2P_SHIFT	= 4,
	SXE2_RX_DESC_EXT_STATUS_RSVD	= 5,
	SXE2_RX_DESC_EXT_STATUS_PKT_REE_SHIFT	= 7,
	SXE2_RX_DESC_EXT_STATUS_ROCE_SHIFT	= 13,
};
#define SXE2_RX_DESC_EXT_STATUS_L2TAG2P_MASK \
			(0x1ULL << SXE2_RX_DESC_EXT_STATUS_L2TAG2P_SHIFT)
#define SXE2_RX_DESC_EXT_STATUS_PKT_REE_MASK \
			(0x3FULL << SXE2_RX_DESC_EXT_STATUS_PKT_REE_SHIFT)
#define SXE2_RX_DESC_EXT_STATUS_ROCE_MASK \
			(0x1ULL << SXE2_RX_DESC_EXT_STATUS_ROCE_SHIFT)

enum sxe2_rx_desc_ipsec_shift {
	SXE2_RX_DESC_IPSEC_PKT_S             = 21,
	SXE2_RX_DESC_IPSEC_ENGINE_S          = 22,
	SXE2_RX_DESC_IPSEC_MODE_S            = 23,
	SXE2_RX_DESC_IPSEC_STATUS_S          = 24,

	SXE2_RX_DESC_IPSEC_LAST
};

enum sxe2_rx_desc_ipsec_status {
	SXE2_RX_DESC_IPSEC_STATUS_SUCCESS           = 0x0,
	SXE2_RX_DESC_IPSEC_STATUS_PKG_OVER_2K       = 0x1,
	SXE2_RX_DESC_IPSEC_STATUS_SPI_IP_INVALID    = 0x2,
	SXE2_RX_DESC_IPSEC_STATUS_SA_INVALID        = 0x3,
	SXE2_RX_DESC_IPSEC_STATUS_NOT_ALIGN         = 0x4,
	SXE2_RX_DESC_IPSEC_STATUS_ICV_ERROR         = 0x5,
	SXE2_RX_DESC_IPSEC_STATUS_BY_PASSH          = 0x6,
	SXE2_RX_DESC_IPSEC_STATUS_MAC_BY_PASSH      = 0x7,
};

#define SXE2_RX_DESC_IPSEC_PKT_MASK \
		(0x1ULL << SXE2_RX_DESC_IPSEC_PKT_S)
#define SXE2_RX_DESC_IPSEC_STATUS_MASK		(0x7)
#define SXE2_RX_DESC_IPSEC_STATUS_VAL_GET(qw2) \
		(((qw2) >> SXE2_RX_DESC_IPSEC_STATUS_S) & \
		SXE2_RX_DESC_IPSEC_STATUS_MASK)

#define SXE2_RX_ERR_BITS 0x3f

#define SXE2_RX_QUEUE_CHECK_INTERVAL_NUM 4

#define SXE2_RX_DESC_RING_ALIGN	\
	(SXE2_ALIGN / sizeof(union sxe2_rx_desc))

#define SXE2_RX_RING_SIZE \
	((SXE2_MAX_RING_DESC + SXE2_RX_PKTS_BURST_BATCH_NUM) * sizeof(union sxe2_rx_desc))

#define SXE2_RX_MAX_DATA_BUF_SIZE	(16 * 1024 - 128)

#endif /* SXE2_TXRX_COMMON_H */
