# SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
# Copyright(c) 2021 Pensando Systems, Inc. All rights reserved.

include $(RTE_SDK)/mk/rte.vars.mk

LIB = librte_common_ionic.a

EXPORT_MAP := rte_common_ionic_version.map

SRCS-y += ionic_common.c
SRCS-y += ionic_common_uio.c

include $(RTE_SDK)/mk/rte.lib.mk
